// Code generated by generator; DO NOT EDIT.

package countrycodes

// ISO 3166-1 alpha-2 country code constants.
// These constants provide compile-time type safety and IDE autocomplete support.
//
// Usage:
//
//	name, _ := Alpha2ToName(countrycodes.Netherlands)
//	alpha3, _ := Alpha2ToAlpha3(countrycodes.France)
const (
	// Andorra - Andorra
	Andorra = "AD"
	// UnitedArabEmirates - United Arab Emirates
	UnitedArabEmirates = "AE"
	// Afghanistan - Afghanistan
	Afghanistan = "AF"
	// AntiguaBarbuda - Antigua and Barbuda
	AntiguaBarbuda = "AG"
	// Anguilla - Anguilla
	Anguilla = "AI"
	// Albania - Albania
	Albania = "AL"
	// Armenia - Armenia
	Armenia = "AM"
	// Angola - Angola
	Angola = "AO"
	// Antarctica - Antarctica
	Antarctica = "AQ"
	// Argentina - Argentina
	Argentina = "AR"
	// AmericanSamoa - American Samoa
	AmericanSamoa = "AS"
	// Austria - Austria
	Austria = "AT"
	// Australia - Australia
	Australia = "AU"
	// Aruba - Aruba
	Aruba = "AW"
	// AlandIslands - Åland Islands
	AlandIslands = "AX"
	// Azerbaijan - Azerbaijan
	Azerbaijan = "AZ"
	// BosniaHerzegovina - Bosnia and Herzegovina
	BosniaHerzegovina = "BA"
	// Barbados - Barbados
	Barbados = "BB"
	// Bangladesh - Bangladesh
	Bangladesh = "BD"
	// Belgium - Belgium
	Belgium = "BE"
	// BurkinaFaso - Burkina Faso
	BurkinaFaso = "BF"
	// Bulgaria - Bulgaria
	Bulgaria = "BG"
	// Bahrain - Bahrain
	Bahrain = "BH"
	// Burundi - Burundi
	Burundi = "BI"
	// Benin - Benin
	Benin = "BJ"
	// SaintBarthelemy - Saint Barthélemy
	SaintBarthelemy = "BL"
	// Bermuda - Bermuda
	Bermuda = "BM"
	// Brunei - Brunei Darussalam
	Brunei = "BN"
	// Bolivia - Bolivia, Plurinational State of
	Bolivia = "BO"
	// CaribbeanNetherlands - Bonaire, Sint Eustatius and Saba
	CaribbeanNetherlands = "BQ"
	// Brazil - Brazil
	Brazil = "BR"
	// Bahamas - Bahamas
	Bahamas = "BS"
	// Bhutan - Bhutan
	Bhutan = "BT"
	// BouvetIsland - Bouvet Island
	BouvetIsland = "BV"
	// Botswana - Botswana
	Botswana = "BW"
	// Belarus - Belarus
	Belarus = "BY"
	// Belize - Belize
	Belize = "BZ"
	// Canada - Canada
	Canada = "CA"
	// CocosIslands - Cocos (Keeling) Islands
	CocosIslands = "CC"
	// CongoDRC - Congo, Democratic Republic of the
	CongoDRC = "CD"
	// CentralAfricanRepublic - Central African Republic
	CentralAfricanRepublic = "CF"
	// CongoBrazzaville - Congo
	CongoBrazzaville = "CG"
	// Switzerland - Switzerland
	Switzerland = "CH"
	// CoteDIvoire - Côte d'Ivoire
	CoteDIvoire = "CI"
	// CookIslands - Cook Islands
	CookIslands = "CK"
	// Chile - Chile
	Chile = "CL"
	// Cameroon - Cameroon
	Cameroon = "CM"
	// China - China
	China = "CN"
	// Colombia - Colombia
	Colombia = "CO"
	// CostaRica - Costa Rica
	CostaRica = "CR"
	// Cuba - Cuba
	Cuba = "CU"
	// CapeVerde - Cabo Verde
	CapeVerde = "CV"
	// Curacao - Curaçao
	Curacao = "CW"
	// ChristmasIsland - Christmas Island
	ChristmasIsland = "CX"
	// Cyprus - Cyprus
	Cyprus = "CY"
	// CzechRepublic - Czechia
	CzechRepublic = "CZ"
	// Germany - Germany
	Germany = "DE"
	// Djibouti - Djibouti
	Djibouti = "DJ"
	// Denmark - Denmark
	Denmark = "DK"
	// Dominica - Dominica
	Dominica = "DM"
	// DominicanRepublic - Dominican Republic
	DominicanRepublic = "DO"
	// Algeria - Algeria
	Algeria = "DZ"
	// Ecuador - Ecuador
	Ecuador = "EC"
	// Estonia - Estonia
	Estonia = "EE"
	// Egypt - Egypt
	Egypt = "EG"
	// WesternSahara - Western Sahara
	WesternSahara = "EH"
	// Eritrea - Eritrea
	Eritrea = "ER"
	// Spain - Spain
	Spain = "ES"
	// Ethiopia - Ethiopia
	Ethiopia = "ET"
	// Finland - Finland
	Finland = "FI"
	// Fiji - Fiji
	Fiji = "FJ"
	// FalklandIslands - Falkland Islands (Malvinas)
	FalklandIslands = "FK"
	// Micronesia - Micronesia, Federated States of
	Micronesia = "FM"
	// FaroeIslands - Faroe Islands
	FaroeIslands = "FO"
	// France - France
	France = "FR"
	// Gabon - Gabon
	Gabon = "GA"
	// UnitedKingdom - United Kingdom of Great Britain and Northern Ireland
	UnitedKingdom = "GB"
	// Grenada - Grenada
	Grenada = "GD"
	// Georgia - Georgia
	Georgia = "GE"
	// FrenchGuiana - French Guiana
	FrenchGuiana = "GF"
	// Guernsey - Guernsey
	Guernsey = "GG"
	// Ghana - Ghana
	Ghana = "GH"
	// Gibraltar - Gibraltar
	Gibraltar = "GI"
	// Greenland - Greenland
	Greenland = "GL"
	// Gambia - Gambia
	Gambia = "GM"
	// Guinea - Guinea
	Guinea = "GN"
	// Guadeloupe - Guadeloupe
	Guadeloupe = "GP"
	// EquatorialGuinea - Equatorial Guinea
	EquatorialGuinea = "GQ"
	// Greece - Greece
	Greece = "GR"
	// SouthGeorgiaAndSouthSandwichIslands - South Georgia and the South Sandwich Islands
	SouthGeorgiaAndSouthSandwichIslands = "GS"
	// Guatemala - Guatemala
	Guatemala = "GT"
	// Guam - Guam
	Guam = "GU"
	// GuineaBissau - Guinea-Bissau
	GuineaBissau = "GW"
	// Guyana - Guyana
	Guyana = "GY"
	// HongKong - Hong Kong
	HongKong = "HK"
	// HeardAndMcDonaldIslands - Heard Island and McDonald Islands
	HeardAndMcDonaldIslands = "HM"
	// Honduras - Honduras
	Honduras = "HN"
	// Croatia - Croatia
	Croatia = "HR"
	// Haiti - Haiti
	Haiti = "HT"
	// Hungary - Hungary
	Hungary = "HU"
	// Indonesia - Indonesia
	Indonesia = "ID"
	// Ireland - Ireland
	Ireland = "IE"
	// Israel - Israel
	Israel = "IL"
	// IsleMan - Isle of Man
	IsleMan = "IM"
	// India - India
	India = "IN"
	// BritishIndianOceanTerritory - British Indian Ocean Territory
	BritishIndianOceanTerritory = "IO"
	// Iraq - Iraq
	Iraq = "IQ"
	// Iran - Iran, Islamic Republic of
	Iran = "IR"
	// Iceland - Iceland
	Iceland = "IS"
	// Italy - Italy
	Italy = "IT"
	// Jersey - Jersey
	Jersey = "JE"
	// Jamaica - Jamaica
	Jamaica = "JM"
	// Jordan - Jordan
	Jordan = "JO"
	// Japan - Japan
	Japan = "JP"
	// Kenya - Kenya
	Kenya = "KE"
	// Kyrgyzstan - Kyrgyzstan
	Kyrgyzstan = "KG"
	// Cambodia - Cambodia
	Cambodia = "KH"
	// Kiribati - Kiribati
	Kiribati = "KI"
	// Comoros - Comoros
	Comoros = "KM"
	// SaintKittsNevis - Saint Kitts and Nevis
	SaintKittsNevis = "KN"
	// NorthKorea - Korea, Democratic People's Republic of
	NorthKorea = "KP"
	// SouthKorea - Korea, Republic of
	SouthKorea = "KR"
	// Kuwait - Kuwait
	Kuwait = "KW"
	// CaymanIslands - Cayman Islands
	CaymanIslands = "KY"
	// Kazakhstan - Kazakhstan
	Kazakhstan = "KZ"
	// Laos - Lao People's Democratic Republic
	Laos = "LA"
	// Lebanon - Lebanon
	Lebanon = "LB"
	// SaintLucia - Saint Lucia
	SaintLucia = "LC"
	// Liechtenstein - Liechtenstein
	Liechtenstein = "LI"
	// SriLanka - Sri Lanka
	SriLanka = "LK"
	// Liberia - Liberia
	Liberia = "LR"
	// Lesotho - Lesotho
	Lesotho = "LS"
	// Lithuania - Lithuania
	Lithuania = "LT"
	// Luxembourg - Luxembourg
	Luxembourg = "LU"
	// Latvia - Latvia
	Latvia = "LV"
	// Libya - Libya
	Libya = "LY"
	// Morocco - Morocco
	Morocco = "MA"
	// Monaco - Monaco
	Monaco = "MC"
	// Moldova - Moldova, Republic of
	Moldova = "MD"
	// Montenegro - Montenegro
	Montenegro = "ME"
	// SaintMartinFrench - Saint Martin (French part)
	SaintMartinFrench = "MF"
	// Madagascar - Madagascar
	Madagascar = "MG"
	// MarshallIslands - Marshall Islands
	MarshallIslands = "MH"
	// NorthMacedonia - North Macedonia
	NorthMacedonia = "MK"
	// Mali - Mali
	Mali = "ML"
	// Myanmar - Myanmar
	Myanmar = "MM"
	// Mongolia - Mongolia
	Mongolia = "MN"
	// Macau - Macao
	Macau = "MO"
	// NorthernMarianaIslands - Northern Mariana Islands
	NorthernMarianaIslands = "MP"
	// Martinique - Martinique
	Martinique = "MQ"
	// Mauritania - Mauritania
	Mauritania = "MR"
	// Montserrat - Montserrat
	Montserrat = "MS"
	// Malta - Malta
	Malta = "MT"
	// Mauritius - Mauritius
	Mauritius = "MU"
	// Maldives - Maldives
	Maldives = "MV"
	// Malawi - Malawi
	Malawi = "MW"
	// Mexico - Mexico
	Mexico = "MX"
	// Malaysia - Malaysia
	Malaysia = "MY"
	// Mozambique - Mozambique
	Mozambique = "MZ"
	// Namibia - Namibia
	Namibia = "NA"
	// NewCaledonia - New Caledonia
	NewCaledonia = "NC"
	// Niger - Niger
	Niger = "NE"
	// NorfolkIsland - Norfolk Island
	NorfolkIsland = "NF"
	// Nigeria - Nigeria
	Nigeria = "NG"
	// Nicaragua - Nicaragua
	Nicaragua = "NI"
	// Netherlands - Netherlands, Kingdom of the
	Netherlands = "NL"
	// Norway - Norway
	Norway = "NO"
	// Nepal - Nepal
	Nepal = "NP"
	// Nauru - Nauru
	Nauru = "NR"
	// Niue - Niue
	Niue = "NU"
	// NewZealand - New Zealand
	NewZealand = "NZ"
	// Oman - Oman
	Oman = "OM"
	// Panama - Panama
	Panama = "PA"
	// Peru - Peru
	Peru = "PE"
	// FrenchPolynesia - French Polynesia
	FrenchPolynesia = "PF"
	// PapuaNewGuinea - Papua New Guinea
	PapuaNewGuinea = "PG"
	// Philippines - Philippines
	Philippines = "PH"
	// Pakistan - Pakistan
	Pakistan = "PK"
	// Poland - Poland
	Poland = "PL"
	// SaintPierreAndMiquelon - Saint Pierre and Miquelon
	SaintPierreAndMiquelon = "PM"
	// Pitcairn - Pitcairn
	Pitcairn = "PN"
	// PuertoRico - Puerto Rico
	PuertoRico = "PR"
	// Palestine - Palestine, State of
	Palestine = "PS"
	// Portugal - Portugal
	Portugal = "PT"
	// Palau - Palau
	Palau = "PW"
	// Paraguay - Paraguay
	Paraguay = "PY"
	// Qatar - Qatar
	Qatar = "QA"
	// Reunion - Réunion
	Reunion = "RE"
	// Romania - Romania
	Romania = "RO"
	// Serbia - Serbia
	Serbia = "RS"
	// Russia - Russian Federation
	Russia = "RU"
	// Rwanda - Rwanda
	Rwanda = "RW"
	// SaudiArabia - Saudi Arabia
	SaudiArabia = "SA"
	// SolomonIslands - Solomon Islands
	SolomonIslands = "SB"
	// Seychelles - Seychelles
	Seychelles = "SC"
	// Sudan - Sudan
	Sudan = "SD"
	// Sweden - Sweden
	Sweden = "SE"
	// Singapore - Singapore
	Singapore = "SG"
	// SaintHelena - Saint Helena, Ascension and Tristan da Cunha
	SaintHelena = "SH"
	// Slovenia - Slovenia
	Slovenia = "SI"
	// SvalbardAndJanMayen - Svalbard and Jan Mayen
	SvalbardAndJanMayen = "SJ"
	// Slovakia - Slovakia
	Slovakia = "SK"
	// SierraLeone - Sierra Leone
	SierraLeone = "SL"
	// SanMarino - San Marino
	SanMarino = "SM"
	// Senegal - Senegal
	Senegal = "SN"
	// Somalia - Somalia
	Somalia = "SO"
	// Suriname - Suriname
	Suriname = "SR"
	// SouthSudan - South Sudan
	SouthSudan = "SS"
	// SaoTomePrincipe - Sao Tome and Principe
	SaoTomePrincipe = "ST"
	// ElSalvador - El Salvador
	ElSalvador = "SV"
	// SintMaartenDutch - Sint Maarten (Dutch part)
	SintMaartenDutch = "SX"
	// Syria - Syrian Arab Republic
	Syria = "SY"
	// Eswatini - Eswatini
	Eswatini = "SZ"
	// TurksAndCaicosIslands - Turks and Caicos Islands
	TurksAndCaicosIslands = "TC"
	// Chad - Chad
	Chad = "TD"
	// FrenchSouthernTerritories - French Southern Territories
	FrenchSouthernTerritories = "TF"
	// Togo - Togo
	Togo = "TG"
	// Thailand - Thailand
	Thailand = "TH"
	// Tajikistan - Tajikistan
	Tajikistan = "TJ"
	// Tokelau - Tokelau
	Tokelau = "TK"
	// TimorLeste - Timor-Leste
	TimorLeste = "TL"
	// Turkmenistan - Turkmenistan
	Turkmenistan = "TM"
	// Tunisia - Tunisia
	Tunisia = "TN"
	// Tonga - Tonga
	Tonga = "TO"
	// Turkiye - Türkiye
	Turkiye = "TR"
	// TrinidadTobago - Trinidad and Tobago
	TrinidadTobago = "TT"
	// Tuvalu - Tuvalu
	Tuvalu = "TV"
	// Taiwan - Taiwan, Province of China
	Taiwan = "TW"
	// Tanzania - Tanzania, United Republic of
	Tanzania = "TZ"
	// Ukraine - Ukraine
	Ukraine = "UA"
	// Uganda - Uganda
	Uganda = "UG"
	// USMinorOutlyingIslands - United States Minor Outlying Islands
	USMinorOutlyingIslands = "UM"
	// UnitedStates - United States of America
	UnitedStates = "US"
	// Uruguay - Uruguay
	Uruguay = "UY"
	// Uzbekistan - Uzbekistan
	Uzbekistan = "UZ"
	// VaticanCity - Holy See
	VaticanCity = "VA"
	// SaintVincentGrenadines - Saint Vincent and the Grenadines
	SaintVincentGrenadines = "VC"
	// Venezuela - Venezuela, Bolivarian Republic of
	Venezuela = "VE"
	// BritishVirginIslands - Virgin Islands (British)
	BritishVirginIslands = "VG"
	// USVirginIslands - Virgin Islands (U.S.)
	USVirginIslands = "VI"
	// Vietnam - Viet Nam
	Vietnam = "VN"
	// Vanuatu - Vanuatu
	Vanuatu = "VU"
	// WallisAndFutuna - Wallis and Futuna
	WallisAndFutuna = "WF"
	// Samoa - Samoa
	Samoa = "WS"
	// Yemen - Yemen
	Yemen = "YE"
	// Mayotte - Mayotte
	Mayotte = "YT"
	// SouthAfrica - South Africa
	SouthAfrica = "ZA"
	// Zambia - Zambia
	Zambia = "ZM"
	// Zimbabwe - Zimbabwe
	Zimbabwe = "ZW"
)
