// Code generated by go generate; DO NOT EDIT.

package countrycodes

// Lookup arrays for O(1) access by numeric country code
var (
	numberToAlpha2 [1000]string
	numberToAlpha3 [1000]string
	numberToName   [1000]string
)

func init() {
	// Initialize the lookup arrays
	numberToAlpha2[20] = "AD"
	numberToAlpha3[20] = "AND"
	numberToName[20] = "Andorra"
	numberToAlpha2[784] = "AE"
	numberToAlpha3[784] = "ARE"
	numberToName[784] = "United Arab Emirates"
	numberToAlpha2[4] = "AF"
	numberToAlpha3[4] = "AFG"
	numberToName[4] = "Afghanistan"
	numberToAlpha2[28] = "AG"
	numberToAlpha3[28] = "ATG"
	numberToName[28] = "Antigua and Barbuda"
	numberToAlpha2[660] = "AI"
	numberToAlpha3[660] = "AIA"
	numberToName[660] = "Anguilla"
	numberToAlpha2[8] = "AL"
	numberToAlpha3[8] = "ALB"
	numberToName[8] = "Albania"
	numberToAlpha2[51] = "AM"
	numberToAlpha3[51] = "ARM"
	numberToName[51] = "Armenia"
	numberToAlpha2[24] = "AO"
	numberToAlpha3[24] = "AGO"
	numberToName[24] = "Angola"
	numberToAlpha2[10] = "AQ"
	numberToAlpha3[10] = "ATA"
	numberToName[10] = "Antarctica"
	numberToAlpha2[32] = "AR"
	numberToAlpha3[32] = "ARG"
	numberToName[32] = "Argentina"
	numberToAlpha2[16] = "AS"
	numberToAlpha3[16] = "ASM"
	numberToName[16] = "American Samoa"
	numberToAlpha2[40] = "AT"
	numberToAlpha3[40] = "AUT"
	numberToName[40] = "Austria"
	numberToAlpha2[36] = "AU"
	numberToAlpha3[36] = "AUS"
	numberToName[36] = "Australia"
	numberToAlpha2[533] = "AW"
	numberToAlpha3[533] = "ABW"
	numberToName[533] = "Aruba"
	numberToAlpha2[248] = "AX"
	numberToAlpha3[248] = "ALA"
	numberToName[248] = "Åland Islands"
	numberToAlpha2[31] = "AZ"
	numberToAlpha3[31] = "AZE"
	numberToName[31] = "Azerbaijan"
	numberToAlpha2[70] = "BA"
	numberToAlpha3[70] = "BIH"
	numberToName[70] = "Bosnia and Herzegovina"
	numberToAlpha2[52] = "BB"
	numberToAlpha3[52] = "BRB"
	numberToName[52] = "Barbados"
	numberToAlpha2[50] = "BD"
	numberToAlpha3[50] = "BGD"
	numberToName[50] = "Bangladesh"
	numberToAlpha2[56] = "BE"
	numberToAlpha3[56] = "BEL"
	numberToName[56] = "Belgium"
	numberToAlpha2[854] = "BF"
	numberToAlpha3[854] = "BFA"
	numberToName[854] = "Burkina Faso"
	numberToAlpha2[100] = "BG"
	numberToAlpha3[100] = "BGR"
	numberToName[100] = "Bulgaria"
	numberToAlpha2[48] = "BH"
	numberToAlpha3[48] = "BHR"
	numberToName[48] = "Bahrain"
	numberToAlpha2[108] = "BI"
	numberToAlpha3[108] = "BDI"
	numberToName[108] = "Burundi"
	numberToAlpha2[204] = "BJ"
	numberToAlpha3[204] = "BEN"
	numberToName[204] = "Benin"
	numberToAlpha2[652] = "BL"
	numberToAlpha3[652] = "BLM"
	numberToName[652] = "Saint Barthélemy"
	numberToAlpha2[60] = "BM"
	numberToAlpha3[60] = "BMU"
	numberToName[60] = "Bermuda"
	numberToAlpha2[96] = "BN"
	numberToAlpha3[96] = "BRN"
	numberToName[96] = "Brunei Darussalam"
	numberToAlpha2[68] = "BO"
	numberToAlpha3[68] = "BOL"
	numberToName[68] = "Bolivia, Plurinational State of"
	numberToAlpha2[535] = "BQ"
	numberToAlpha3[535] = "BES"
	numberToName[535] = "Bonaire, Sint Eustatius and Saba"
	numberToAlpha2[76] = "BR"
	numberToAlpha3[76] = "BRA"
	numberToName[76] = "Brazil"
	numberToAlpha2[44] = "BS"
	numberToAlpha3[44] = "BHS"
	numberToName[44] = "Bahamas"
	numberToAlpha2[64] = "BT"
	numberToAlpha3[64] = "BTN"
	numberToName[64] = "Bhutan"
	numberToAlpha2[74] = "BV"
	numberToAlpha3[74] = "BVT"
	numberToName[74] = "Bouvet Island"
	numberToAlpha2[72] = "BW"
	numberToAlpha3[72] = "BWA"
	numberToName[72] = "Botswana"
	numberToAlpha2[112] = "BY"
	numberToAlpha3[112] = "BLR"
	numberToName[112] = "Belarus"
	numberToAlpha2[84] = "BZ"
	numberToAlpha3[84] = "BLZ"
	numberToName[84] = "Belize"
	numberToAlpha2[124] = "CA"
	numberToAlpha3[124] = "CAN"
	numberToName[124] = "Canada"
	numberToAlpha2[166] = "CC"
	numberToAlpha3[166] = "CCK"
	numberToName[166] = "Cocos (Keeling) Islands"
	numberToAlpha2[180] = "CD"
	numberToAlpha3[180] = "COD"
	numberToName[180] = "Congo, Democratic Republic of the"
	numberToAlpha2[140] = "CF"
	numberToAlpha3[140] = "CAF"
	numberToName[140] = "Central African Republic"
	numberToAlpha2[178] = "CG"
	numberToAlpha3[178] = "COG"
	numberToName[178] = "Congo"
	numberToAlpha2[756] = "CH"
	numberToAlpha3[756] = "CHE"
	numberToName[756] = "Switzerland"
	numberToAlpha2[384] = "CI"
	numberToAlpha3[384] = "CIV"
	numberToName[384] = "Côte d'Ivoire"
	numberToAlpha2[184] = "CK"
	numberToAlpha3[184] = "COK"
	numberToName[184] = "Cook Islands"
	numberToAlpha2[152] = "CL"
	numberToAlpha3[152] = "CHL"
	numberToName[152] = "Chile"
	numberToAlpha2[120] = "CM"
	numberToAlpha3[120] = "CMR"
	numberToName[120] = "Cameroon"
	numberToAlpha2[156] = "CN"
	numberToAlpha3[156] = "CHN"
	numberToName[156] = "China"
	numberToAlpha2[170] = "CO"
	numberToAlpha3[170] = "COL"
	numberToName[170] = "Colombia"
	numberToAlpha2[188] = "CR"
	numberToAlpha3[188] = "CRI"
	numberToName[188] = "Costa Rica"
	numberToAlpha2[192] = "CU"
	numberToAlpha3[192] = "CUB"
	numberToName[192] = "Cuba"
	numberToAlpha2[132] = "CV"
	numberToAlpha3[132] = "CPV"
	numberToName[132] = "Cabo Verde"
	numberToAlpha2[531] = "CW"
	numberToAlpha3[531] = "CUW"
	numberToName[531] = "Curaçao"
	numberToAlpha2[162] = "CX"
	numberToAlpha3[162] = "CXR"
	numberToName[162] = "Christmas Island"
	numberToAlpha2[196] = "CY"
	numberToAlpha3[196] = "CYP"
	numberToName[196] = "Cyprus"
	numberToAlpha2[203] = "CZ"
	numberToAlpha3[203] = "CZE"
	numberToName[203] = "Czechia"
	numberToAlpha2[276] = "DE"
	numberToAlpha3[276] = "DEU"
	numberToName[276] = "Germany"
	numberToAlpha2[262] = "DJ"
	numberToAlpha3[262] = "DJI"
	numberToName[262] = "Djibouti"
	numberToAlpha2[208] = "DK"
	numberToAlpha3[208] = "DNK"
	numberToName[208] = "Denmark"
	numberToAlpha2[212] = "DM"
	numberToAlpha3[212] = "DMA"
	numberToName[212] = "Dominica"
	numberToAlpha2[214] = "DO"
	numberToAlpha3[214] = "DOM"
	numberToName[214] = "Dominican Republic"
	numberToAlpha2[12] = "DZ"
	numberToAlpha3[12] = "DZA"
	numberToName[12] = "Algeria"
	numberToAlpha2[218] = "EC"
	numberToAlpha3[218] = "ECU"
	numberToName[218] = "Ecuador"
	numberToAlpha2[233] = "EE"
	numberToAlpha3[233] = "EST"
	numberToName[233] = "Estonia"
	numberToAlpha2[818] = "EG"
	numberToAlpha3[818] = "EGY"
	numberToName[818] = "Egypt"
	numberToAlpha2[732] = "EH"
	numberToAlpha3[732] = "ESH"
	numberToName[732] = "Western Sahara"
	numberToAlpha2[232] = "ER"
	numberToAlpha3[232] = "ERI"
	numberToName[232] = "Eritrea"
	numberToAlpha2[724] = "ES"
	numberToAlpha3[724] = "ESP"
	numberToName[724] = "Spain"
	numberToAlpha2[231] = "ET"
	numberToAlpha3[231] = "ETH"
	numberToName[231] = "Ethiopia"
	numberToAlpha2[246] = "FI"
	numberToAlpha3[246] = "FIN"
	numberToName[246] = "Finland"
	numberToAlpha2[242] = "FJ"
	numberToAlpha3[242] = "FJI"
	numberToName[242] = "Fiji"
	numberToAlpha2[238] = "FK"
	numberToAlpha3[238] = "FLK"
	numberToName[238] = "Falkland Islands (Malvinas)"
	numberToAlpha2[583] = "FM"
	numberToAlpha3[583] = "FSM"
	numberToName[583] = "Micronesia, Federated States of"
	numberToAlpha2[234] = "FO"
	numberToAlpha3[234] = "FRO"
	numberToName[234] = "Faroe Islands"
	numberToAlpha2[250] = "FR"
	numberToAlpha3[250] = "FRA"
	numberToName[250] = "France"
	numberToAlpha2[266] = "GA"
	numberToAlpha3[266] = "GAB"
	numberToName[266] = "Gabon"
	numberToAlpha2[826] = "GB"
	numberToAlpha3[826] = "GBR"
	numberToName[826] = "United Kingdom of Great Britain and Northern Ireland"
	numberToAlpha2[308] = "GD"
	numberToAlpha3[308] = "GRD"
	numberToName[308] = "Grenada"
	numberToAlpha2[268] = "GE"
	numberToAlpha3[268] = "GEO"
	numberToName[268] = "Georgia"
	numberToAlpha2[254] = "GF"
	numberToAlpha3[254] = "GUF"
	numberToName[254] = "French Guiana"
	numberToAlpha2[831] = "GG"
	numberToAlpha3[831] = "GGY"
	numberToName[831] = "Guernsey"
	numberToAlpha2[288] = "GH"
	numberToAlpha3[288] = "GHA"
	numberToName[288] = "Ghana"
	numberToAlpha2[292] = "GI"
	numberToAlpha3[292] = "GIB"
	numberToName[292] = "Gibraltar"
	numberToAlpha2[304] = "GL"
	numberToAlpha3[304] = "GRL"
	numberToName[304] = "Greenland"
	numberToAlpha2[270] = "GM"
	numberToAlpha3[270] = "GMB"
	numberToName[270] = "Gambia"
	numberToAlpha2[324] = "GN"
	numberToAlpha3[324] = "GIN"
	numberToName[324] = "Guinea"
	numberToAlpha2[312] = "GP"
	numberToAlpha3[312] = "GLP"
	numberToName[312] = "Guadeloupe"
	numberToAlpha2[226] = "GQ"
	numberToAlpha3[226] = "GNQ"
	numberToName[226] = "Equatorial Guinea"
	numberToAlpha2[300] = "GR"
	numberToAlpha3[300] = "GRC"
	numberToName[300] = "Greece"
	numberToAlpha2[239] = "GS"
	numberToAlpha3[239] = "SGS"
	numberToName[239] = "South Georgia and the South Sandwich Islands"
	numberToAlpha2[320] = "GT"
	numberToAlpha3[320] = "GTM"
	numberToName[320] = "Guatemala"
	numberToAlpha2[316] = "GU"
	numberToAlpha3[316] = "GUM"
	numberToName[316] = "Guam"
	numberToAlpha2[624] = "GW"
	numberToAlpha3[624] = "GNB"
	numberToName[624] = "Guinea-Bissau"
	numberToAlpha2[328] = "GY"
	numberToAlpha3[328] = "GUY"
	numberToName[328] = "Guyana"
	numberToAlpha2[344] = "HK"
	numberToAlpha3[344] = "HKG"
	numberToName[344] = "Hong Kong"
	numberToAlpha2[334] = "HM"
	numberToAlpha3[334] = "HMD"
	numberToName[334] = "Heard Island and McDonald Islands"
	numberToAlpha2[340] = "HN"
	numberToAlpha3[340] = "HND"
	numberToName[340] = "Honduras"
	numberToAlpha2[191] = "HR"
	numberToAlpha3[191] = "HRV"
	numberToName[191] = "Croatia"
	numberToAlpha2[332] = "HT"
	numberToAlpha3[332] = "HTI"
	numberToName[332] = "Haiti"
	numberToAlpha2[348] = "HU"
	numberToAlpha3[348] = "HUN"
	numberToName[348] = "Hungary"
	numberToAlpha2[360] = "ID"
	numberToAlpha3[360] = "IDN"
	numberToName[360] = "Indonesia"
	numberToAlpha2[372] = "IE"
	numberToAlpha3[372] = "IRL"
	numberToName[372] = "Ireland"
	numberToAlpha2[376] = "IL"
	numberToAlpha3[376] = "ISR"
	numberToName[376] = "Israel"
	numberToAlpha2[833] = "IM"
	numberToAlpha3[833] = "IMN"
	numberToName[833] = "Isle of Man"
	numberToAlpha2[356] = "IN"
	numberToAlpha3[356] = "IND"
	numberToName[356] = "India"
	numberToAlpha2[86] = "IO"
	numberToAlpha3[86] = "IOT"
	numberToName[86] = "British Indian Ocean Territory"
	numberToAlpha2[368] = "IQ"
	numberToAlpha3[368] = "IRQ"
	numberToName[368] = "Iraq"
	numberToAlpha2[364] = "IR"
	numberToAlpha3[364] = "IRN"
	numberToName[364] = "Iran, Islamic Republic of"
	numberToAlpha2[352] = "IS"
	numberToAlpha3[352] = "ISL"
	numberToName[352] = "Iceland"
	numberToAlpha2[380] = "IT"
	numberToAlpha3[380] = "ITA"
	numberToName[380] = "Italy"
	numberToAlpha2[832] = "JE"
	numberToAlpha3[832] = "JEY"
	numberToName[832] = "Jersey"
	numberToAlpha2[388] = "JM"
	numberToAlpha3[388] = "JAM"
	numberToName[388] = "Jamaica"
	numberToAlpha2[400] = "JO"
	numberToAlpha3[400] = "JOR"
	numberToName[400] = "Jordan"
	numberToAlpha2[392] = "JP"
	numberToAlpha3[392] = "JPN"
	numberToName[392] = "Japan"
	numberToAlpha2[404] = "KE"
	numberToAlpha3[404] = "KEN"
	numberToName[404] = "Kenya"
	numberToAlpha2[417] = "KG"
	numberToAlpha3[417] = "KGZ"
	numberToName[417] = "Kyrgyzstan"
	numberToAlpha2[116] = "KH"
	numberToAlpha3[116] = "KHM"
	numberToName[116] = "Cambodia"
	numberToAlpha2[296] = "KI"
	numberToAlpha3[296] = "KIR"
	numberToName[296] = "Kiribati"
	numberToAlpha2[174] = "KM"
	numberToAlpha3[174] = "COM"
	numberToName[174] = "Comoros"
	numberToAlpha2[659] = "KN"
	numberToAlpha3[659] = "KNA"
	numberToName[659] = "Saint Kitts and Nevis"
	numberToAlpha2[408] = "KP"
	numberToAlpha3[408] = "PRK"
	numberToName[408] = "Korea, Democratic People's Republic of"
	numberToAlpha2[410] = "KR"
	numberToAlpha3[410] = "KOR"
	numberToName[410] = "Korea, Republic of"
	numberToAlpha2[414] = "KW"
	numberToAlpha3[414] = "KWT"
	numberToName[414] = "Kuwait"
	numberToAlpha2[136] = "KY"
	numberToAlpha3[136] = "CYM"
	numberToName[136] = "Cayman Islands"
	numberToAlpha2[398] = "KZ"
	numberToAlpha3[398] = "KAZ"
	numberToName[398] = "Kazakhstan"
	numberToAlpha2[418] = "LA"
	numberToAlpha3[418] = "LAO"
	numberToName[418] = "Lao People's Democratic Republic"
	numberToAlpha2[422] = "LB"
	numberToAlpha3[422] = "LBN"
	numberToName[422] = "Lebanon"
	numberToAlpha2[662] = "LC"
	numberToAlpha3[662] = "LCA"
	numberToName[662] = "Saint Lucia"
	numberToAlpha2[438] = "LI"
	numberToAlpha3[438] = "LIE"
	numberToName[438] = "Liechtenstein"
	numberToAlpha2[144] = "LK"
	numberToAlpha3[144] = "LKA"
	numberToName[144] = "Sri Lanka"
	numberToAlpha2[430] = "LR"
	numberToAlpha3[430] = "LBR"
	numberToName[430] = "Liberia"
	numberToAlpha2[426] = "LS"
	numberToAlpha3[426] = "LSO"
	numberToName[426] = "Lesotho"
	numberToAlpha2[440] = "LT"
	numberToAlpha3[440] = "LTU"
	numberToName[440] = "Lithuania"
	numberToAlpha2[442] = "LU"
	numberToAlpha3[442] = "LUX"
	numberToName[442] = "Luxembourg"
	numberToAlpha2[428] = "LV"
	numberToAlpha3[428] = "LVA"
	numberToName[428] = "Latvia"
	numberToAlpha2[434] = "LY"
	numberToAlpha3[434] = "LBY"
	numberToName[434] = "Libya"
	numberToAlpha2[504] = "MA"
	numberToAlpha3[504] = "MAR"
	numberToName[504] = "Morocco"
	numberToAlpha2[492] = "MC"
	numberToAlpha3[492] = "MCO"
	numberToName[492] = "Monaco"
	numberToAlpha2[498] = "MD"
	numberToAlpha3[498] = "MDA"
	numberToName[498] = "Moldova, Republic of"
	numberToAlpha2[499] = "ME"
	numberToAlpha3[499] = "MNE"
	numberToName[499] = "Montenegro"
	numberToAlpha2[663] = "MF"
	numberToAlpha3[663] = "MAF"
	numberToName[663] = "Saint Martin (French part)"
	numberToAlpha2[450] = "MG"
	numberToAlpha3[450] = "MDG"
	numberToName[450] = "Madagascar"
	numberToAlpha2[584] = "MH"
	numberToAlpha3[584] = "MHL"
	numberToName[584] = "Marshall Islands"
	numberToAlpha2[807] = "MK"
	numberToAlpha3[807] = "MKD"
	numberToName[807] = "North Macedonia"
	numberToAlpha2[466] = "ML"
	numberToAlpha3[466] = "MLI"
	numberToName[466] = "Mali"
	numberToAlpha2[104] = "MM"
	numberToAlpha3[104] = "MMR"
	numberToName[104] = "Myanmar"
	numberToAlpha2[496] = "MN"
	numberToAlpha3[496] = "MNG"
	numberToName[496] = "Mongolia"
	numberToAlpha2[446] = "MO"
	numberToAlpha3[446] = "MAC"
	numberToName[446] = "Macao"
	numberToAlpha2[580] = "MP"
	numberToAlpha3[580] = "MNP"
	numberToName[580] = "Northern Mariana Islands"
	numberToAlpha2[474] = "MQ"
	numberToAlpha3[474] = "MTQ"
	numberToName[474] = "Martinique"
	numberToAlpha2[478] = "MR"
	numberToAlpha3[478] = "MRT"
	numberToName[478] = "Mauritania"
	numberToAlpha2[500] = "MS"
	numberToAlpha3[500] = "MSR"
	numberToName[500] = "Montserrat"
	numberToAlpha2[470] = "MT"
	numberToAlpha3[470] = "MLT"
	numberToName[470] = "Malta"
	numberToAlpha2[480] = "MU"
	numberToAlpha3[480] = "MUS"
	numberToName[480] = "Mauritius"
	numberToAlpha2[462] = "MV"
	numberToAlpha3[462] = "MDV"
	numberToName[462] = "Maldives"
	numberToAlpha2[454] = "MW"
	numberToAlpha3[454] = "MWI"
	numberToName[454] = "Malawi"
	numberToAlpha2[484] = "MX"
	numberToAlpha3[484] = "MEX"
	numberToName[484] = "Mexico"
	numberToAlpha2[458] = "MY"
	numberToAlpha3[458] = "MYS"
	numberToName[458] = "Malaysia"
	numberToAlpha2[508] = "MZ"
	numberToAlpha3[508] = "MOZ"
	numberToName[508] = "Mozambique"
	numberToAlpha2[516] = "NA"
	numberToAlpha3[516] = "NAM"
	numberToName[516] = "Namibia"
	numberToAlpha2[540] = "NC"
	numberToAlpha3[540] = "NCL"
	numberToName[540] = "New Caledonia"
	numberToAlpha2[562] = "NE"
	numberToAlpha3[562] = "NER"
	numberToName[562] = "Niger"
	numberToAlpha2[574] = "NF"
	numberToAlpha3[574] = "NFK"
	numberToName[574] = "Norfolk Island"
	numberToAlpha2[566] = "NG"
	numberToAlpha3[566] = "NGA"
	numberToName[566] = "Nigeria"
	numberToAlpha2[558] = "NI"
	numberToAlpha3[558] = "NIC"
	numberToName[558] = "Nicaragua"
	numberToAlpha2[528] = "NL"
	numberToAlpha3[528] = "NLD"
	numberToName[528] = "Netherlands, Kingdom of the"
	numberToAlpha2[578] = "NO"
	numberToAlpha3[578] = "NOR"
	numberToName[578] = "Norway"
	numberToAlpha2[524] = "NP"
	numberToAlpha3[524] = "NPL"
	numberToName[524] = "Nepal"
	numberToAlpha2[520] = "NR"
	numberToAlpha3[520] = "NRU"
	numberToName[520] = "Nauru"
	numberToAlpha2[570] = "NU"
	numberToAlpha3[570] = "NIU"
	numberToName[570] = "Niue"
	numberToAlpha2[554] = "NZ"
	numberToAlpha3[554] = "NZL"
	numberToName[554] = "New Zealand"
	numberToAlpha2[512] = "OM"
	numberToAlpha3[512] = "OMN"
	numberToName[512] = "Oman"
	numberToAlpha2[591] = "PA"
	numberToAlpha3[591] = "PAN"
	numberToName[591] = "Panama"
	numberToAlpha2[604] = "PE"
	numberToAlpha3[604] = "PER"
	numberToName[604] = "Peru"
	numberToAlpha2[258] = "PF"
	numberToAlpha3[258] = "PYF"
	numberToName[258] = "French Polynesia"
	numberToAlpha2[598] = "PG"
	numberToAlpha3[598] = "PNG"
	numberToName[598] = "Papua New Guinea"
	numberToAlpha2[608] = "PH"
	numberToAlpha3[608] = "PHL"
	numberToName[608] = "Philippines"
	numberToAlpha2[586] = "PK"
	numberToAlpha3[586] = "PAK"
	numberToName[586] = "Pakistan"
	numberToAlpha2[616] = "PL"
	numberToAlpha3[616] = "POL"
	numberToName[616] = "Poland"
	numberToAlpha2[666] = "PM"
	numberToAlpha3[666] = "SPM"
	numberToName[666] = "Saint Pierre and Miquelon"
	numberToAlpha2[612] = "PN"
	numberToAlpha3[612] = "PCN"
	numberToName[612] = "Pitcairn"
	numberToAlpha2[630] = "PR"
	numberToAlpha3[630] = "PRI"
	numberToName[630] = "Puerto Rico"
	numberToAlpha2[275] = "PS"
	numberToAlpha3[275] = "PSE"
	numberToName[275] = "Palestine, State of"
	numberToAlpha2[620] = "PT"
	numberToAlpha3[620] = "PRT"
	numberToName[620] = "Portugal"
	numberToAlpha2[585] = "PW"
	numberToAlpha3[585] = "PLW"
	numberToName[585] = "Palau"
	numberToAlpha2[600] = "PY"
	numberToAlpha3[600] = "PRY"
	numberToName[600] = "Paraguay"
	numberToAlpha2[634] = "QA"
	numberToAlpha3[634] = "QAT"
	numberToName[634] = "Qatar"
	numberToAlpha2[638] = "RE"
	numberToAlpha3[638] = "REU"
	numberToName[638] = "Réunion"
	numberToAlpha2[642] = "RO"
	numberToAlpha3[642] = "ROU"
	numberToName[642] = "Romania"
	numberToAlpha2[688] = "RS"
	numberToAlpha3[688] = "SRB"
	numberToName[688] = "Serbia"
	numberToAlpha2[643] = "RU"
	numberToAlpha3[643] = "RUS"
	numberToName[643] = "Russian Federation"
	numberToAlpha2[646] = "RW"
	numberToAlpha3[646] = "RWA"
	numberToName[646] = "Rwanda"
	numberToAlpha2[682] = "SA"
	numberToAlpha3[682] = "SAU"
	numberToName[682] = "Saudi Arabia"
	numberToAlpha2[90] = "SB"
	numberToAlpha3[90] = "SLB"
	numberToName[90] = "Solomon Islands"
	numberToAlpha2[690] = "SC"
	numberToAlpha3[690] = "SYC"
	numberToName[690] = "Seychelles"
	numberToAlpha2[729] = "SD"
	numberToAlpha3[729] = "SDN"
	numberToName[729] = "Sudan"
	numberToAlpha2[752] = "SE"
	numberToAlpha3[752] = "SWE"
	numberToName[752] = "Sweden"
	numberToAlpha2[702] = "SG"
	numberToAlpha3[702] = "SGP"
	numberToName[702] = "Singapore"
	numberToAlpha2[654] = "SH"
	numberToAlpha3[654] = "SHN"
	numberToName[654] = "Saint Helena, Ascension and Tristan da Cunha"
	numberToAlpha2[705] = "SI"
	numberToAlpha3[705] = "SVN"
	numberToName[705] = "Slovenia"
	numberToAlpha2[744] = "SJ"
	numberToAlpha3[744] = "SJM"
	numberToName[744] = "Svalbard and Jan Mayen"
	numberToAlpha2[703] = "SK"
	numberToAlpha3[703] = "SVK"
	numberToName[703] = "Slovakia"
	numberToAlpha2[694] = "SL"
	numberToAlpha3[694] = "SLE"
	numberToName[694] = "Sierra Leone"
	numberToAlpha2[674] = "SM"
	numberToAlpha3[674] = "SMR"
	numberToName[674] = "San Marino"
	numberToAlpha2[686] = "SN"
	numberToAlpha3[686] = "SEN"
	numberToName[686] = "Senegal"
	numberToAlpha2[706] = "SO"
	numberToAlpha3[706] = "SOM"
	numberToName[706] = "Somalia"
	numberToAlpha2[740] = "SR"
	numberToAlpha3[740] = "SUR"
	numberToName[740] = "Suriname"
	numberToAlpha2[728] = "SS"
	numberToAlpha3[728] = "SSD"
	numberToName[728] = "South Sudan"
	numberToAlpha2[678] = "ST"
	numberToAlpha3[678] = "STP"
	numberToName[678] = "Sao Tome and Principe"
	numberToAlpha2[222] = "SV"
	numberToAlpha3[222] = "SLV"
	numberToName[222] = "El Salvador"
	numberToAlpha2[534] = "SX"
	numberToAlpha3[534] = "SXM"
	numberToName[534] = "Sint Maarten (Dutch part)"
	numberToAlpha2[760] = "SY"
	numberToAlpha3[760] = "SYR"
	numberToName[760] = "Syrian Arab Republic"
	numberToAlpha2[748] = "SZ"
	numberToAlpha3[748] = "SWZ"
	numberToName[748] = "Eswatini"
	numberToAlpha2[796] = "TC"
	numberToAlpha3[796] = "TCA"
	numberToName[796] = "Turks and Caicos Islands"
	numberToAlpha2[148] = "TD"
	numberToAlpha3[148] = "TCD"
	numberToName[148] = "Chad"
	numberToAlpha2[260] = "TF"
	numberToAlpha3[260] = "ATF"
	numberToName[260] = "French Southern Territories"
	numberToAlpha2[768] = "TG"
	numberToAlpha3[768] = "TGO"
	numberToName[768] = "Togo"
	numberToAlpha2[764] = "TH"
	numberToAlpha3[764] = "THA"
	numberToName[764] = "Thailand"
	numberToAlpha2[762] = "TJ"
	numberToAlpha3[762] = "TJK"
	numberToName[762] = "Tajikistan"
	numberToAlpha2[772] = "TK"
	numberToAlpha3[772] = "TKL"
	numberToName[772] = "Tokelau"
	numberToAlpha2[626] = "TL"
	numberToAlpha3[626] = "TLS"
	numberToName[626] = "Timor-Leste"
	numberToAlpha2[795] = "TM"
	numberToAlpha3[795] = "TKM"
	numberToName[795] = "Turkmenistan"
	numberToAlpha2[788] = "TN"
	numberToAlpha3[788] = "TUN"
	numberToName[788] = "Tunisia"
	numberToAlpha2[776] = "TO"
	numberToAlpha3[776] = "TON"
	numberToName[776] = "Tonga"
	numberToAlpha2[792] = "TR"
	numberToAlpha3[792] = "TUR"
	numberToName[792] = "Türkiye"
	numberToAlpha2[780] = "TT"
	numberToAlpha3[780] = "TTO"
	numberToName[780] = "Trinidad and Tobago"
	numberToAlpha2[798] = "TV"
	numberToAlpha3[798] = "TUV"
	numberToName[798] = "Tuvalu"
	numberToAlpha2[158] = "TW"
	numberToAlpha3[158] = "TWN"
	numberToName[158] = "Taiwan, Province of China"
	numberToAlpha2[834] = "TZ"
	numberToAlpha3[834] = "TZA"
	numberToName[834] = "Tanzania, United Republic of"
	numberToAlpha2[804] = "UA"
	numberToAlpha3[804] = "UKR"
	numberToName[804] = "Ukraine"
	numberToAlpha2[800] = "UG"
	numberToAlpha3[800] = "UGA"
	numberToName[800] = "Uganda"
	numberToAlpha2[581] = "UM"
	numberToAlpha3[581] = "UMI"
	numberToName[581] = "United States Minor Outlying Islands"
	numberToAlpha2[840] = "US"
	numberToAlpha3[840] = "USA"
	numberToName[840] = "United States of America"
	numberToAlpha2[858] = "UY"
	numberToAlpha3[858] = "URY"
	numberToName[858] = "Uruguay"
	numberToAlpha2[860] = "UZ"
	numberToAlpha3[860] = "UZB"
	numberToName[860] = "Uzbekistan"
	numberToAlpha2[336] = "VA"
	numberToAlpha3[336] = "VAT"
	numberToName[336] = "Holy See"
	numberToAlpha2[670] = "VC"
	numberToAlpha3[670] = "VCT"
	numberToName[670] = "Saint Vincent and the Grenadines"
	numberToAlpha2[862] = "VE"
	numberToAlpha3[862] = "VEN"
	numberToName[862] = "Venezuela, Bolivarian Republic of"
	numberToAlpha2[92] = "VG"
	numberToAlpha3[92] = "VGB"
	numberToName[92] = "Virgin Islands (British)"
	numberToAlpha2[850] = "VI"
	numberToAlpha3[850] = "VIR"
	numberToName[850] = "Virgin Islands (U.S.)"
	numberToAlpha2[704] = "VN"
	numberToAlpha3[704] = "VNM"
	numberToName[704] = "Viet Nam"
	numberToAlpha2[548] = "VU"
	numberToAlpha3[548] = "VUT"
	numberToName[548] = "Vanuatu"
	numberToAlpha2[876] = "WF"
	numberToAlpha3[876] = "WLF"
	numberToName[876] = "Wallis and Futuna"
	numberToAlpha2[882] = "WS"
	numberToAlpha3[882] = "WSM"
	numberToName[882] = "Samoa"
	numberToAlpha2[887] = "YE"
	numberToAlpha3[887] = "YEM"
	numberToName[887] = "Yemen"
	numberToAlpha2[175] = "YT"
	numberToAlpha3[175] = "MYT"
	numberToName[175] = "Mayotte"
	numberToAlpha2[710] = "ZA"
	numberToAlpha3[710] = "ZAF"
	numberToName[710] = "South Africa"
	numberToAlpha2[894] = "ZM"
	numberToAlpha3[894] = "ZMB"
	numberToName[894] = "Zambia"
	numberToAlpha2[716] = "ZW"
	numberToAlpha3[716] = "ZWE"
	numberToName[716] = "Zimbabwe"
}

// Lookup maps for O(1) case-insensitive access using packed keys
var (
	// Maps packed 2-char keys to numeric codes as integers
	alpha2ToNumberIntMap = map[uint16]int{
		0x6461: 20,
		0x6561: 784,
		0x6661: 4,
		0x6761: 28,
		0x6961: 660,
		0x6c61: 8,
		0x6d61: 51,
		0x6f61: 24,
		0x7161: 10,
		0x7261: 32,
		0x7361: 16,
		0x7461: 40,
		0x7561: 36,
		0x7761: 533,
		0x7861: 248,
		0x7a61: 31,
		0x6162: 70,
		0x6262: 52,
		0x6462: 50,
		0x6562: 56,
		0x6662: 854,
		0x6762: 100,
		0x6862: 48,
		0x6962: 108,
		0x6a62: 204,
		0x6c62: 652,
		0x6d62: 60,
		0x6e62: 96,
		0x6f62: 68,
		0x7162: 535,
		0x7262: 76,
		0x7362: 44,
		0x7462: 64,
		0x7662: 74,
		0x7762: 72,
		0x7962: 112,
		0x7a62: 84,
		0x6163: 124,
		0x6363: 166,
		0x6463: 180,
		0x6663: 140,
		0x6763: 178,
		0x6863: 756,
		0x6963: 384,
		0x6b63: 184,
		0x6c63: 152,
		0x6d63: 120,
		0x6e63: 156,
		0x6f63: 170,
		0x7263: 188,
		0x7563: 192,
		0x7663: 132,
		0x7763: 531,
		0x7863: 162,
		0x7963: 196,
		0x7a63: 203,
		0x6564: 276,
		0x6a64: 262,
		0x6b64: 208,
		0x6d64: 212,
		0x6f64: 214,
		0x7a64: 12,
		0x6365: 218,
		0x6565: 233,
		0x6765: 818,
		0x6865: 732,
		0x7265: 232,
		0x7365: 724,
		0x7465: 231,
		0x6966: 246,
		0x6a66: 242,
		0x6b66: 238,
		0x6d66: 583,
		0x6f66: 234,
		0x7266: 250,
		0x6167: 266,
		0x6267: 826,
		0x6467: 308,
		0x6567: 268,
		0x6667: 254,
		0x6767: 831,
		0x6867: 288,
		0x6967: 292,
		0x6c67: 304,
		0x6d67: 270,
		0x6e67: 324,
		0x7067: 312,
		0x7167: 226,
		0x7267: 300,
		0x7367: 239,
		0x7467: 320,
		0x7567: 316,
		0x7767: 624,
		0x7967: 328,
		0x6b68: 344,
		0x6d68: 334,
		0x6e68: 340,
		0x7268: 191,
		0x7468: 332,
		0x7568: 348,
		0x6469: 360,
		0x6569: 372,
		0x6c69: 376,
		0x6d69: 833,
		0x6e69: 356,
		0x6f69: 86,
		0x7169: 368,
		0x7269: 364,
		0x7369: 352,
		0x7469: 380,
		0x656a: 832,
		0x6d6a: 388,
		0x6f6a: 400,
		0x706a: 392,
		0x656b: 404,
		0x676b: 417,
		0x686b: 116,
		0x696b: 296,
		0x6d6b: 174,
		0x6e6b: 659,
		0x706b: 408,
		0x726b: 410,
		0x776b: 414,
		0x796b: 136,
		0x7a6b: 398,
		0x616c: 418,
		0x626c: 422,
		0x636c: 662,
		0x696c: 438,
		0x6b6c: 144,
		0x726c: 430,
		0x736c: 426,
		0x746c: 440,
		0x756c: 442,
		0x766c: 428,
		0x796c: 434,
		0x616d: 504,
		0x636d: 492,
		0x646d: 498,
		0x656d: 499,
		0x666d: 663,
		0x676d: 450,
		0x686d: 584,
		0x6b6d: 807,
		0x6c6d: 466,
		0x6d6d: 104,
		0x6e6d: 496,
		0x6f6d: 446,
		0x706d: 580,
		0x716d: 474,
		0x726d: 478,
		0x736d: 500,
		0x746d: 470,
		0x756d: 480,
		0x766d: 462,
		0x776d: 454,
		0x786d: 484,
		0x796d: 458,
		0x7a6d: 508,
		0x616e: 516,
		0x636e: 540,
		0x656e: 562,
		0x666e: 574,
		0x676e: 566,
		0x696e: 558,
		0x6c6e: 528,
		0x6f6e: 578,
		0x706e: 524,
		0x726e: 520,
		0x756e: 570,
		0x7a6e: 554,
		0x6d6f: 512,
		0x6170: 591,
		0x6570: 604,
		0x6670: 258,
		0x6770: 598,
		0x6870: 608,
		0x6b70: 586,
		0x6c70: 616,
		0x6d70: 666,
		0x6e70: 612,
		0x7270: 630,
		0x7370: 275,
		0x7470: 620,
		0x7770: 585,
		0x7970: 600,
		0x6171: 634,
		0x6572: 638,
		0x6f72: 642,
		0x7372: 688,
		0x7572: 643,
		0x7772: 646,
		0x6173: 682,
		0x6273: 90,
		0x6373: 690,
		0x6473: 729,
		0x6573: 752,
		0x6773: 702,
		0x6873: 654,
		0x6973: 705,
		0x6a73: 744,
		0x6b73: 703,
		0x6c73: 694,
		0x6d73: 674,
		0x6e73: 686,
		0x6f73: 706,
		0x7273: 740,
		0x7373: 728,
		0x7473: 678,
		0x7673: 222,
		0x7873: 534,
		0x7973: 760,
		0x7a73: 748,
		0x6374: 796,
		0x6474: 148,
		0x6674: 260,
		0x6774: 768,
		0x6874: 764,
		0x6a74: 762,
		0x6b74: 772,
		0x6c74: 626,
		0x6d74: 795,
		0x6e74: 788,
		0x6f74: 776,
		0x7274: 792,
		0x7474: 780,
		0x7674: 798,
		0x7774: 158,
		0x7a74: 834,
		0x6175: 804,
		0x6775: 800,
		0x6d75: 581,
		0x7375: 840,
		0x7975: 858,
		0x7a75: 860,
		0x6176: 336,
		0x6376: 670,
		0x6576: 862,
		0x6776: 92,
		0x6976: 850,
		0x6e76: 704,
		0x7576: 548,
		0x6677: 876,
		0x7377: 882,
		0x6579: 887,
		0x7479: 175,
		0x617a: 710,
		0x6d7a: 894,
		0x777a: 716,
	}

	// Maps packed 3-char keys to numeric codes as integers
	alpha3ToNumberIntMap = map[uint32]int{
		0x646e61: 20,
		0x657261: 784,
		0x676661: 4,
		0x677461: 28,
		0x616961: 660,
		0x626c61: 8,
		0x6d7261: 51,
		0x6f6761: 24,
		0x617461: 10,
		0x677261: 32,
		0x6d7361: 16,
		0x747561: 40,
		0x737561: 36,
		0x776261: 533,
		0x616c61: 248,
		0x657a61: 31,
		0x686962: 70,
		0x627262: 52,
		0x646762: 50,
		0x6c6562: 56,
		0x616662: 854,
		0x726762: 100,
		0x726862: 48,
		0x696462: 108,
		0x6e6562: 204,
		0x6d6c62: 652,
		0x756d62: 60,
		0x6e7262: 96,
		0x6c6f62: 68,
		0x736562: 535,
		0x617262: 76,
		0x736862: 44,
		0x6e7462: 64,
		0x747662: 74,
		0x617762: 72,
		0x726c62: 112,
		0x7a6c62: 84,
		0x6e6163: 124,
		0x6b6363: 166,
		0x646f63: 180,
		0x666163: 140,
		0x676f63: 178,
		0x656863: 756,
		0x766963: 384,
		0x6b6f63: 184,
		0x6c6863: 152,
		0x726d63: 120,
		0x6e6863: 156,
		0x6c6f63: 170,
		0x697263: 188,
		0x627563: 192,
		0x767063: 132,
		0x777563: 531,
		0x727863: 162,
		0x707963: 196,
		0x657a63: 203,
		0x756564: 276,
		0x696a64: 262,
		0x6b6e64: 208,
		0x616d64: 212,
		0x6d6f64: 214,
		0x617a64: 12,
		0x756365: 218,
		0x747365: 233,
		0x796765: 818,
		0x687365: 732,
		0x697265: 232,
		0x707365: 724,
		0x687465: 231,
		0x6e6966: 246,
		0x696a66: 242,
		0x6b6c66: 238,
		0x6d7366: 583,
		0x6f7266: 234,
		0x617266: 250,
		0x626167: 266,
		0x726267: 826,
		0x647267: 308,
		0x6f6567: 268,
		0x667567: 254,
		0x796767: 831,
		0x616867: 288,
		0x626967: 292,
		0x6c7267: 304,
		0x626d67: 270,
		0x6e6967: 324,
		0x706c67: 312,
		0x716e67: 226,
		0x637267: 300,
		0x736773: 239,
		0x6d7467: 320,
		0x6d7567: 316,
		0x626e67: 624,
		0x797567: 328,
		0x676b68: 344,
		0x646d68: 334,
		0x646e68: 340,
		0x767268: 191,
		0x697468: 332,
		0x6e7568: 348,
		0x6e6469: 360,
		0x6c7269: 372,
		0x727369: 376,
		0x6e6d69: 833,
		0x646e69: 356,
		0x746f69: 86,
		0x717269: 368,
		0x6e7269: 364,
		0x6c7369: 352,
		0x617469: 380,
		0x79656a: 832,
		0x6d616a: 388,
		0x726f6a: 400,
		0x6e706a: 392,
		0x6e656b: 404,
		0x7a676b: 417,
		0x6d686b: 116,
		0x72696b: 296,
		0x6d6f63: 174,
		0x616e6b: 659,
		0x6b7270: 408,
		0x726f6b: 410,
		0x74776b: 414,
		0x6d7963: 136,
		0x7a616b: 398,
		0x6f616c: 418,
		0x6e626c: 422,
		0x61636c: 662,
		0x65696c: 438,
		0x616b6c: 144,
		0x72626c: 430,
		0x6f736c: 426,
		0x75746c: 440,
		0x78756c: 442,
		0x61766c: 428,
		0x79626c: 434,
		0x72616d: 504,
		0x6f636d: 492,
		0x61646d: 498,
		0x656e6d: 499,
		0x66616d: 663,
		0x67646d: 450,
		0x6c686d: 584,
		0x646b6d: 807,
		0x696c6d: 466,
		0x726d6d: 104,
		0x676e6d: 496,
		0x63616d: 446,
		0x706e6d: 580,
		0x71746d: 474,
		0x74726d: 478,
		0x72736d: 500,
		0x746c6d: 470,
		0x73756d: 480,
		0x76646d: 462,
		0x69776d: 454,
		0x78656d: 484,
		0x73796d: 458,
		0x7a6f6d: 508,
		0x6d616e: 516,
		0x6c636e: 540,
		0x72656e: 562,
		0x6b666e: 574,
		0x61676e: 566,
		0x63696e: 558,
		0x646c6e: 528,
		0x726f6e: 578,
		0x6c706e: 524,
		0x75726e: 520,
		0x75696e: 570,
		0x6c7a6e: 554,
		0x6e6d6f: 512,
		0x6e6170: 591,
		0x726570: 604,
		0x667970: 258,
		0x676e70: 598,
		0x6c6870: 608,
		0x6b6170: 586,
		0x6c6f70: 616,
		0x6d7073: 666,
		0x6e6370: 612,
		0x697270: 630,
		0x657370: 275,
		0x747270: 620,
		0x776c70: 585,
		0x797270: 600,
		0x746171: 634,
		0x756572: 638,
		0x756f72: 642,
		0x627273: 688,
		0x737572: 643,
		0x617772: 646,
		0x756173: 682,
		0x626c73: 90,
		0x637973: 690,
		0x6e6473: 729,
		0x657773: 752,
		0x706773: 702,
		0x6e6873: 654,
		0x6e7673: 705,
		0x6d6a73: 744,
		0x6b7673: 703,
		0x656c73: 694,
		0x726d73: 674,
		0x6e6573: 686,
		0x6d6f73: 706,
		0x727573: 740,
		0x647373: 728,
		0x707473: 678,
		0x766c73: 222,
		0x6d7873: 534,
		0x727973: 760,
		0x7a7773: 748,
		0x616374: 796,
		0x646374: 148,
		0x667461: 260,
		0x6f6774: 768,
		0x616874: 764,
		0x6b6a74: 762,
		0x6c6b74: 772,
		0x736c74: 626,
		0x6d6b74: 795,
		0x6e7574: 788,
		0x6e6f74: 776,
		0x727574: 792,
		0x6f7474: 780,
		0x767574: 798,
		0x6e7774: 158,
		0x617a74: 834,
		0x726b75: 804,
		0x616775: 800,
		0x696d75: 581,
		0x617375: 840,
		0x797275: 858,
		0x627a75: 860,
		0x746176: 336,
		0x746376: 670,
		0x6e6576: 862,
		0x626776: 92,
		0x726976: 850,
		0x6d6e76: 704,
		0x747576: 548,
		0x666c77: 876,
		0x6d7377: 882,
		0x6d6579: 887,
		0x74796d: 175,
		0x66617a: 710,
		0x626d7a: 894,
		0x65777a: 716,
	}
)

// Alpha2ToNumberInt converts an ISO 3166-1 alpha-2 code to its UN M.49 numeric code as an integer.
//
// This function performs an O(1) lookup using packed keys for zero-allocation,
// case-insensitive matching. This is the fastest way to get a numeric code as an integer.
// The input is case-insensitive.
//
// Parameters:
//   - code: ISO 3166-1 alpha-2 code (e.g., "US", "us", "GB", "gb")
//
// Returns:
//   - int: The UN M.49 numeric code as integer (e.g., 840 for "US")
//   - bool: true if the conversion succeeded, false if the input code is invalid
//
// Example:
//
//	if num, ok := Alpha2ToNumberInt("us"); ok {
//	    fmt.Printf("Numeric code: %d\n", num) // Output: Numeric code: 840
//	}
func Alpha2ToNumberInt(code string) (int, bool) {
	if key, ok := key2(code); ok {
		if v, ok := alpha2ToNumberIntMap[key]; ok {
			return v, true
		}
	}
	return 0, false
}

// Alpha3ToNumberInt converts an ISO 3166-1 alpha-3 code to its UN M.49 numeric code as an integer.
//
// This function performs an O(1) lookup using packed keys for zero-allocation,
// case-insensitive matching. This is the fastest way to get a numeric code as an integer.
// The input is case-insensitive.
//
// Parameters:
//   - code: ISO 3166-1 alpha-3 code (e.g., "USA", "usa", "GBR", "gbr")
//
// Returns:
//   - int: The UN M.49 numeric code as integer (e.g., 840 for "USA")
//   - bool: true if the conversion succeeded, false if the input code is invalid
//
// Example:
//
//	if num, ok := Alpha3ToNumberInt("usa"); ok {
//	    fmt.Printf("Numeric code: %d\n", num) // Output: Numeric code: 840
//	}
func Alpha3ToNumberInt(code string) (int, bool) {
	if key, ok := key3(code); ok {
		if v, ok := alpha3ToNumberIntMap[key]; ok {
			return v, true
		}
	}
	return 0, false
}

// NumberIntToAlpha2 converts a UN M.49 numeric code (as integer) to its ISO 3166-1 alpha-2 code.
//
// This function uses direct array indexing for O(1) performance with zero allocations.
// This is the fastest method for numeric to alpha conversions when you have an integer input.
//
// Parameters:
//   - code: UN M.49 numeric code as integer (e.g., 840, 4, 826)
//
// Returns:
//   - string: The corresponding alpha-2 code if found
//   - bool: true if the conversion succeeded, false if the input code is invalid
//
// Example:
//
//	if alpha2, ok := NumberIntToAlpha2(840); ok {
//	    fmt.Println(alpha2) // Output: US
//	}
//
// Performance: Sub-nanosecond lookup time with zero allocations.
func NumberIntToAlpha2(code int) (string, bool) {
	if code < 0 || code >= len(numberToAlpha2) || numberToAlpha2[code] == "" {
		return "", false
	}
	return numberToAlpha2[code], true
}

// NumberIntToAlpha3 converts a UN M.49 numeric code (as integer) to its ISO 3166-1 alpha-3 code.
//
// This function uses direct array indexing for O(1) performance with zero allocations.
// This is the fastest method for numeric to alpha conversions when you have an integer input.
//
// Parameters:
//   - code: UN M.49 numeric code as integer (e.g., 840, 4, 826)
//
// Returns:
//   - string: The corresponding alpha-3 code if found
//   - bool: true if the conversion succeeded, false if the input code is invalid
//
// Example:
//
//	if alpha3, ok := NumberIntToAlpha3(840); ok {
//	    fmt.Println(alpha3) // Output: USA
//	}
//
// Performance: Sub-nanosecond lookup time with zero allocations.
func NumberIntToAlpha3(code int) (string, bool) {
	if code < 0 || code >= len(numberToAlpha3) || numberToAlpha3[code] == "" {
		return "", false
	}
	return numberToAlpha3[code], true
}

// NumberIntToName retrieves the country name for a UN M.49 numeric code (as integer).
//
// This function uses direct array indexing for O(1) performance with zero allocations.
// This is the fastest method to get a country name from a numeric code.
//
// Parameters:
//   - code: UN M.49 numeric code as integer (e.g., 840, 4, 826)
//
// Returns:
//   - string: The country name if found
//   - bool: true if the code exists, false otherwise
//
// Example:
//
//	if name, ok := NumberIntToName(840); ok {
//	    fmt.Println(name) // Output: United States of America
//	}
//
// Performance: Sub-nanosecond lookup time with zero allocations.
func NumberIntToName(code int) (string, bool) {
	if code < 0 || code >= len(numberToName) || numberToName[code] == "" {
		return "", false
	}
	return numberToName[code], true
}

// GetByNumberInt retrieves complete country information by UN M.49 numeric code (as integer).
//
// This function uses direct array indexing for O(1) performance with zero allocations.
// This is the fastest method to get full country information from a numeric code.
//
// Parameters:
//   - code: UN M.49 numeric code as integer (e.g., 840, 4, 826)
//
// Returns:
//   - Country: Complete country information if found
//   - bool: true if the country code exists, false otherwise
//
// Example:
//
//	if country, ok := GetByNumberInt(840); ok {
//	    fmt.Printf("%s has alpha-2 code %s\n", country.Name, country.Alpha2)
//	}
//
// Performance: Sub-nanosecond lookup time with zero allocations.
func GetByNumberInt(code int) (Country, bool) {
	if code < 0 || code >= len(countryByNumber) || countryByNumber[code] == nil {
		return Country{}, false
	}
	return *countryByNumber[code], true
}

// IsValidNumberInt checks if the given integer is a valid UN M.49 numeric code.
//
// This function uses direct array bounds checking for O(1) performance.
//
// Parameters:
//   - code: Integer to validate as UN M.49 numeric code
//
// Returns:
//   - bool: true if the code is a valid UN M.49 numeric code, false otherwise
//
// Example:
//
//	if IsValidNumberInt(840) {
//	    fmt.Println("Valid UN M.49 code")
//	}
//
// Performance: Sub-nanosecond validation with zero allocations.
func IsValidNumberInt(code int) bool {
	return code >= 0 && code < len(numberToAlpha2) && numberToAlpha2[code] != ""
}
