// Code generated by go generate; DO NOT EDIT.

package countrycodes

// Hash table size - power of 2 for efficient masking
const nameMask = 511 // 512 slots

// Hash table slots - stores hash values for collision detection
var nameSlotHash = [nameMask + 1]uint64{
	0,                    // 0
	5894117516372923905,  // 1
	8837016197204702722,  // 2
	10786833398502536195, // 3
	0,                    // 4
	8886311939899388933,  // 5
	15151327443089351174, // 6
	0,                    // 7
	4457335828964980744,  // 8
	0,                    // 9
	13173211440978612746, // 10
	0,                    // 11
	0,                    // 12
	0,                    // 13
	12894467625587270158, // 14
	0,                    // 15
	0,                    // 16
	0,                    // 17
	0,                    // 18
	0,                    // 19
	2263733512633220116,  // 20
	6634099357242468373,  // 21
	0,                    // 22
	0,                    // 23
	0,                    // 24
	0,                    // 25
	0,                    // 26
	0,                    // 27
	13543803095653512220, // 28
	14129155636494470173, // 29
	0,                    // 30
	0,                    // 31
	33537478060931616,    // 32
	0,                    // 33
	2560967865422100514,  // 34
	0,                    // 35
	0,                    // 36
	0,                    // 37
	10497633871475099686, // 38
	0,                    // 39
	0,                    // 40
	8226984714281203241,  // 41
	0,                    // 42
	16610333573711035947, // 43
	0,                    // 44
	1715234723727860781,  // 45
	0,                    // 46
	12464238620624610863, // 47
	7073531543352033328,  // 48
	0,                    // 49
	0,                    // 50
	0,                    // 51
	0,                    // 52
	5822578265668284469,  // 53
	3609884217172683830,  // 54
	11977876972761153590, // 55
	9794817434854216758,  // 56
	0,                    // 57
	3591284937151838266,  // 58
	3989905908805479995,  // 59
	3320535071928677434,  // 60
	0,                    // 61
	17181881246361548350, // 62
	9342900354280641598,  // 63
	2836754095552510528,  // 64
	17416114374894496318, // 65
	0,                    // 66
	9005055640343592003,  // 67
	10168335993876910148, // 68
	17825813290276355141, // 69
	5917501471149478981,  // 70
	12306369075703197765, // 71
	13885189079825627208, // 72
	7307693887344116297,  // 73
	8393281176483405386,  // 74
	10395583764678099529, // 75
	9494007545031093324,  // 76
	5818033301668368973,  // 77
	4709266623553521742,  // 78
	2296864938757286479,  // 79
	1735243441629588558,  // 80
	12315096375224390216, // 81
	0,                    // 82
	0,                    // 83
	0,                    // 84
	0,                    // 85
	0,                    // 86
	0,                    // 87
	0,                    // 88
	0,                    // 89
	3153319527248242266,  // 90
	3863226094884046939,  // 91
	13362569129217001563, // 92
	3375251263703327837,  // 93
	0,                    // 94
	0,                    // 95
	0,                    // 96
	0,                    // 97
	6968883441508906594,  // 98
	2704121657533613667,  // 99
	16124137969661526115, // 100
	16304382317815381603, // 101
	0,                    // 102
	0,                    // 103
	0,                    // 104
	5848966686688771177,  // 105
	0,                    // 106
	0,                    // 107
	0,                    // 108
	702225668909077613,   // 109
	3972702774636638830,  // 110
	0,                    // 111
	0,                    // 112
	7322954759491597937,  // 113
	15823305540940071025, // 114
	0,                    // 115
	0,                    // 116
	9089649125855276661,  // 117
	9049554122295801462,  // 118
	599303933032684151,   // 119
	6764308533420523640,  // 120
	0,                    // 121
	13339456176456808058, // 122
	9985871721717941370,  // 123
	0,                    // 124
	0,                    // 125
	0,                    // 126
	0,                    // 127
	0,                    // 128
	3010954049584495233,  // 129
	16850933279005017218, // 130
	0,                    // 131
	11218953723944670340, // 132
	17332345731810605700, // 133
	8481507496389986950,  // 134
	4962988846794576519,  // 135
	0,                    // 136
	0,                    // 137
	0,                    // 138
	0,                    // 139
	0,                    // 140
	0,                    // 141
	0,                    // 142
	14273149878490297487, // 143
	5881734209398905488,  // 144
	0,                    // 145
	6896524686504341138,  // 146
	0,                    // 147
	8142443973603698836,  // 148
	1299026572849258645,  // 149
	13317743755288982166, // 150
	15443145227994337940, // 151
	4973867938688774295,  // 152
	0,                    // 153
	0,                    // 154
	0,                    // 155
	0,                    // 156
	0,                    // 157
	3114861530939903134,  // 158
	0,                    // 159
	0,                    // 160
	10653059611277255329, // 161
	15628019049705837730, // 162
	17466522804089660579, // 163
	5627793740398625444,  // 164
	1263659800061553316,  // 165
	6382308614166612130,  // 166
	241018004124598951,   // 167
	6669514860856933544,  // 168
	7567558501948175017,  // 169
	7051239293285783210,  // 170
	14151025294576644267, // 171
	12013236366155762860, // 172
	0,                    // 173
	0,                    // 174
	0,                    // 175
	5360823917902204592,  // 176
	5297286356299102896,  // 177
	16230922345654662833, // 178
	6023773008316483760,  // 179
	6384920966082999988,  // 180
	8639959135376385203,  // 181
	12191934003691604662, // 182
	3196373717895571639,  // 183
	8743961866518695605,  // 184
	0,                    // 185
	7734355477490691770,  // 186
	10903331458259583163, // 187
	7492687445743254204,  // 188
	5626880830674400442,  // 189
	0,                    // 190
	0,                    // 191
	0,                    // 192
	0,                    // 193
	3443267924872891586,  // 194
	8144981333929450179,  // 195
	0,                    // 196
	0,                    // 197
	0,                    // 198
	0,                    // 199
	4335618451944348360,  // 200
	15940617454953022665, // 201
	6001789913585793738,  // 202
	7622269713257840329,  // 203
	1906120776301850316,  // 204
	6295353949192384204,  // 205
	4864476431978757838,  // 206
	16493967068252753100, // 207
	17233648948425661648, // 208
	1839610508127035089,  // 209
	0,                    // 210
	0,                    // 211
	0,                    // 212
	0,                    // 213
	0,                    // 214
	0,                    // 215
	0,                    // 216
	7529977014041480409,  // 217
	0,                    // 218
	11885308543367450843, // 219
	2953720802892200668,  // 220
	10009758836536834269, // 221
	2020691735283220190,  // 222
	0,                    // 223
	0,                    // 224
	0,                    // 225
	0,                    // 226
	0,                    // 227
	0,                    // 228
	0,                    // 229
	0,                    // 230
	10120024525366626023, // 231
	0,                    // 232
	4492227427482643689,  // 233
	7071833897398453994,  // 234
	0,                    // 235
	16094130433803604204, // 236
	6057780601176991468,  // 237
	5729047398403327726,  // 238
	13445797548123833583, // 239
	18119401308236242158, // 240
	0,                    // 241
	0,                    // 242
	15408451961228104435, // 243
	573622583683603188,   // 244
	15551156418737011445, // 245
	15888954151163355892, // 246
	1819157869012668151,  // 247
	4095417705002173688,  // 248
	0,                    // 249
	0,                    // 250
	6897430602390506235,  // 251
	0,                    // 252
	9576666841343355133,  // 253
	0,                    // 254
	0,                    // 255
	0,                    // 256
	0,                    // 257
	11102417358101861634, // 258
	0,                    // 259
	36425801359644420,    // 260
	10985861895340809476, // 261
	0,                    // 262
	0,                    // 263
	12560401498868130568, // 264
	693648719710917385,   // 265
	4078105849649592586,  // 266
	11526831411497806091, // 267
	1257231485924906764,  // 268
	12060468279587036427, // 269
	1621216377344376590,  // 270
	0,                    // 271
	4455840202055219984,  // 272
	15017977298457136401, // 273
	0,                    // 274
	0,                    // 275
	0,                    // 276
	0,                    // 277
	11875635733059253526, // 278
	0,                    // 279
	0,                    // 280
	0,                    // 281
	5815170622858091290,  // 282
	0,                    // 283
	0,                    // 284
	0,                    // 285
	9105928506909763870,  // 286
	0,                    // 287
	0,                    // 288
	7218044042314328865,  // 289
	0,                    // 290
	0,                    // 291
	0,                    // 292
	10798601634577194277, // 293
	669336201890689830,   // 294
	18402952120277258533, // 295
	200892687881317672,   // 296
	0,                    // 297
	13397905578146770730, // 298
	6081256165242244395,  // 299
	0,                    // 300
	14905721930165609261, // 301
	9522962431417879854,  // 302
	0,                    // 303
	0,                    // 304
	0,                    // 305
	0,                    // 306
	11205558535498941747, // 307
	0,                    // 308
	0,                    // 309
	0,                    // 310
	12353897810878883639, // 311
	2920711826612257592,  // 312
	0,                    // 313
	6471812697952299834,  // 314
	0,                    // 315
	0,                    // 316
	0,                    // 317
	0,                    // 318
	5035109500423632703,  // 319
	15722777684609332544, // 320
	0,                    // 321
	10104032705433113922, // 322
	0,                    // 323
	0,                    // 324
	8747625388276664645,  // 325
	16054575105846097734, // 326
	0,                    // 327
	9909121156424715080,  // 328
	0,                    // 329
	0,                    // 330
	17366719762676283723, // 331
	5503228941717201740,  // 332
	2516554016207994189,  // 333
	0,                    // 334
	0,                    // 335
	0,                    // 336
	0,                    // 337
	0,                    // 338
	0,                    // 339
	0,                    // 340
	0,                    // 341
	570590069494584662,   // 342
	13446616535958322519, // 343
	12529367719908485976, // 344
	12717032908839098712, // 345
	0,                    // 346
	0,                    // 347
	0,                    // 348
	12290292011992178013, // 349
	0,                    // 350
	0,                    // 351
	0,                    // 352
	12687141330155245921, // 353
	15530074438752401761, // 354
	0,                    // 355
	0,                    // 356
	0,                    // 357
	0,                    // 358
	0,                    // 359
	13822149362034894184, // 360
	0,                    // 361
	5488805185730899306,  // 362
	0,                    // 363
	1337348796885871980,  // 364
	0,                    // 365
	0,                    // 366
	3358730053925850479,  // 367
	1935526106162727792,  // 368
	0,                    // 369
	0,                    // 370
	0,                    // 371
	964626602981869428,   // 372
	14100499799703743349, // 373
	1941667467941190006,  // 374
	0,                    // 375
	5391311031578628472,  // 376
	0,                    // 377
	10319927759654317434, // 378
	0,                    // 379
	0,                    // 380
	0,                    // 381
	0,                    // 382
	0,                    // 383
	0,                    // 384
	0,                    // 385
	14438702778212003714, // 386
	5480348142102113666,  // 387
	0,                    // 388
	2099987714593617797,  // 389
	0,                    // 390
	0,                    // 391
	0,                    // 392
	13826573967614440329, // 393
	15778683930187608458, // 394
	0,                    // 395
	0,                    // 396
	4069957101918602637,  // 397
	13088540265425757070, // 398
	5771419142390206863,  // 399
	0,                    // 400
	0,                    // 401
	0,                    // 402
	0,                    // 403
	0,                    // 404
	0,                    // 405
	0,                    // 406
	0,                    // 407
	0,                    // 408
	0,                    // 409
	0,                    // 410
	0,                    // 411
	0,                    // 412
	0,                    // 413
	1304273637529241502,  // 414
	3616684269308398495,  // 415
	17830079675357093792, // 416
	6677211765809549217,  // 417
	0,                    // 418
	0,                    // 419
	0,                    // 420
	0,                    // 421
	0,                    // 422
	8141309935239916967,  // 423
	2479803019314245032,  // 424
	5494797831109689256,  // 425
	11222029520376751017, // 426
	2823670597741103018,  // 427
	2859463422093561255,  // 428
	0,                    // 429
	0,                    // 430
	16190311456973067695, // 431
	5554565321740405167,  // 432
	18264846147410644401, // 433
	9002020328805082031,  // 434
	5862733393679527347,  // 435
	14760782015747698100, // 436
	18277985588765110708, // 437
	7244263614581186486,  // 438
	0,                    // 439
	7038466446204601272,  // 440
	0,                    // 441
	0,                    // 442
	17483991424668749755, // 443
	0,                    // 444
	0,                    // 445
	0,                    // 446
	0,                    // 447
	0,                    // 448
	17562691644084643777, // 449
	11541563060266291649, // 450
	0,                    // 451
	12609701975479026628, // 452
	0,                    // 453
	0,                    // 454
	16326826762383619527, // 455
	11632668952001082823, // 456
	0,                    // 457
	0,                    // 458
	0,                    // 459
	7272514664822135756,  // 460
	11298717196843633613, // 461
	0,                    // 462
	0,                    // 463
	0,                    // 464
	702685297843063249,   // 465
	14636070381942928338, // 466
	0,                    // 467
	10613031083816024532, // 468
	0,                    // 469
	14278140813389923286, // 470
	322421243322991574,   // 471
	3368510063055301079,  // 472
	0,                    // 473
	0,                    // 474
	5066867251204796379,  // 475
	0,                    // 476
	0,                    // 477
	0,                    // 478
	0,                    // 479
	9305504290350283744,  // 480
	6911240005527788001,  // 481
	11469952728196193762, // 482
	8241564141139114977,  // 483
	0,                    // 484
	13644779952080292837, // 485
	373014967232612838,   // 486
	0,                    // 487
	12462032000687129064, // 488
	0,                    // 489
	0,                    // 490
	0,                    // 491
	7505737252862439404,  // 492
	6685851869701603820,  // 493
	0,                    // 494
	17552930671465247215, // 495
	0,                    // 496
	0,                    // 497
	0,                    // 498
	0,                    // 499
	0,                    // 500
	0,                    // 501
	4550335407622113270,  // 502
	8294738524935981046,  // 503
	0,                    // 504
	0,                    // 505
	0,                    // 506
	0,                    // 507
	7759648299516855804,  // 508
	0,                    // 509
	4250509236457576446,  // 510
	4404950709511795711,  // 511
}

// Hash table indices - points to nameKeys/nameVals arrays (0xFFFF = empty)
var nameSlotIdx = [nameMask + 1]uint16{
	0xFFFF, // 0
	32,     // 1
	98,     // 2
	59,     // 3
	0xFFFF, // 4
	178,    // 5
	219,    // 6
	0xFFFF, // 7
	107,    // 8
	0xFFFF, // 9
	20,     // 10
	0xFFFF, // 11
	0xFFFF, // 12
	0xFFFF, // 13
	202,    // 14
	0xFFFF, // 15
	0xFFFF, // 16
	0xFFFF, // 17
	0xFFFF, // 18
	0xFFFF, // 19
	144,    // 20
	130,    // 21
	0xFFFF, // 22
	0xFFFF, // 23
	0xFFFF, // 24
	0xFFFF, // 25
	0xFFFF, // 26
	0xFFFF, // 27
	15,     // 28
	172,    // 29
	0xFFFF, // 30
	0xFFFF, // 31
	76,     // 32
	0xFFFF, // 33
	171,    // 34
	0xFFFF, // 35
	0xFFFF, // 36
	0xFFFF, // 37
	134,    // 38
	0xFFFF, // 39
	0xFFFF, // 40
	133,    // 41
	0xFFFF, // 42
	7,      // 43
	0xFFFF, // 44
	196,    // 45
	0xFFFF, // 46
	48,     // 47
	47,     // 48
	0xFFFF, // 49
	0xFFFF, // 50
	0xFFFF, // 51
	0xFFFF, // 52
	141,    // 53
	36,     // 54
	40,     // 55
	117,    // 56
	0xFFFF, // 57
	38,     // 58
	116,    // 59
	199,    // 60
	0xFFFF, // 61
	14,     // 62
	56,     // 63
	4,      // 64
	97,     // 65
	0xFFFF, // 66
	69,     // 67
	13,     // 68
	8,      // 69
	43,     // 70
	70,     // 71
	71,     // 72
	180,    // 73
	86,     // 74
	228,    // 75
	104,    // 76
	205,    // 77
	23,     // 78
	189,    // 79
	221,    // 80
	235,    // 81
	0xFFFF, // 82
	0xFFFF, // 83
	0xFFFF, // 84
	0xFFFF, // 85
	0xFFFF, // 86
	0xFFFF, // 87
	0xFFFF, // 88
	0xFFFF, // 89
	74,     // 90
	37,     // 91
	113,    // 92
	240,    // 93
	0xFFFF, // 94
	0xFFFF, // 95
	0xFFFF, // 96
	0xFFFF, // 97
	93,     // 98
	44,     // 99
	173,    // 100
	211,    // 101
	0xFFFF, // 102
	0xFFFF, // 103
	0xFFFF, // 104
	100,    // 105
	0xFFFF, // 106
	0xFFFF, // 107
	0xFFFF, // 108
	110,    // 109
	9,      // 110
	0xFFFF, // 111
	0xFFFF, // 112
	41,     // 113
	77,     // 114
	0xFFFF, // 115
	0xFFFF, // 116
	118,    // 117
	151,    // 118
	103,    // 119
	106,    // 120
	0xFFFF, // 121
	25,     // 122
	245,    // 123
	0xFFFF, // 124
	0xFFFF, // 125
	0xFFFF, // 126
	0xFFFF, // 127
	0xFFFF, // 128
	2,      // 129
	157,    // 130
	0xFFFF, // 131
	81,     // 132
	200,    // 133
	159,    // 134
	183,    // 135
	0xFFFF, // 136
	0xFFFF, // 137
	0xFFFF, // 138
	0xFFFF, // 139
	0xFFFF, // 140
	0xFFFF, // 141
	0xFFFF, // 142
	112,    // 143
	153,    // 144
	0xFFFF, // 145
	149,    // 146
	0xFFFF, // 147
	184,    // 148
	28,     // 149
	3,      // 150
	198,    // 151
	241,    // 152
	0xFFFF, // 153
	0xFFFF, // 154
	0xFFFF, // 155
	0xFFFF, // 156
	0xFFFF, // 157
	165,    // 158
	0xFFFF, // 159
	0xFFFF, // 160
	99,     // 161
	137,    // 162
	114,    // 163
	18,     // 164
	61,     // 165
	177,    // 166
	119,    // 167
	138,    // 168
	12,     // 169
	193,    // 170
	26,     // 171
	226,    // 172
	0xFFFF, // 173
	0xFFFF, // 174
	0xFFFF, // 175
	11,     // 176
	63,     // 177
	66,     // 178
	89,     // 179
	94,     // 180
	203,    // 181
	208,    // 182
	30,     // 183
	227,    // 184
	0xFFFF, // 185
	88,     // 186
	105,    // 187
	21,     // 188
	222,    // 189
	0xFFFF, // 190
	0xFFFF, // 191
	0xFFFF, // 192
	0xFFFF, // 193
	216,    // 194
	139,    // 195
	0xFFFF, // 196
	0xFFFF, // 197
	0xFFFF, // 198
	0xFFFF, // 199
	224,    // 200
	167,    // 201
	126,    // 202
	201,    // 203
	109,    // 204
	231,    // 205
	67,     // 206
	248,    // 207
	10,     // 208
	232,    // 209
	0xFFFF, // 210
	0xFFFF, // 211
	0xFFFF, // 212
	0xFFFF, // 213
	0xFFFF, // 214
	0xFFFF, // 215
	0xFFFF, // 216
	136,    // 217
	0xFFFF, // 218
	210,    // 219
	101,    // 220
	225,    // 221
	0,      // 222
	0xFFFF, // 223
	0xFFFF, // 224
	0xFFFF, // 225
	0xFFFF, // 226
	0xFFFF, // 227
	0xFFFF, // 228
	0xFFFF, // 229
	0xFFFF, // 230
	242,    // 231
	0xFFFF, // 232
	83,     // 233
	45,     // 234
	0xFFFF, // 235
	51,     // 236
	84,     // 237
	161,    // 238
	175,    // 239
	223,    // 240
	0xFFFF, // 241
	0xFFFF, // 242
	239,    // 243
	29,     // 244
	24,     // 245
	129,    // 246
	82,     // 247
	195,    // 248
	0xFFFF, // 249
	0xFFFF, // 250
	234,    // 251
	0xFFFF, // 252
	140,    // 253
	0xFFFF, // 254
	0xFFFF, // 255
	0xFFFF, // 256
	0xFFFF, // 257
	90,     // 258
	0xFFFF, // 259
	72,     // 260
	204,    // 261
	0xFFFF, // 262
	0xFFFF, // 263
	155,    // 264
	244,    // 265
	135,    // 266
	57,     // 267
	127,    // 268
	146,    // 269
	194,    // 270
	0xFFFF, // 271
	53,     // 272
	236,    // 273
	0xFFFF, // 274
	0xFFFF, // 275
	0xFFFF, // 276
	0xFFFF, // 277
	217,    // 278
	0xFFFF, // 279
	0xFFFF, // 280
	0xFFFF, // 281
	128,    // 282
	0xFFFF, // 283
	0xFFFF, // 284
	0xFFFF, // 285
	186,    // 286
	0xFFFF, // 287
	0xFFFF, // 288
	207,    // 289
	0xFFFF, // 290
	0xFFFF, // 291
	0xFFFF, // 292
	213,    // 293
	169,    // 294
	247,    // 295
	49,     // 296
	0xFFFF, // 297
	31,     // 298
	5,      // 299
	0xFFFF, // 300
	96,     // 301
	68,     // 302
	0xFFFF, // 303
	0xFFFF, // 304
	0xFFFF, // 305
	0xFFFF, // 306
	124,    // 307
	0xFFFF, // 308
	0xFFFF, // 309
	0xFFFF, // 310
	181,    // 311
	145,    // 312
	0xFFFF, // 313
	55,     // 314
	0xFFFF, // 315
	0xFFFF, // 316
	0xFFFF, // 317
	0xFFFF, // 318
	206,    // 319
	73,     // 320
	0xFFFF, // 321
	179,    // 322
	0xFFFF, // 323
	0xFFFF, // 324
	108,    // 325
	168,    // 326
	0xFFFF, // 327
	187,    // 328
	0xFFFF, // 329
	0xFFFF, // 330
	80,     // 331
	50,     // 332
	185,    // 333
	0xFFFF, // 334
	0xFFFF, // 335
	0xFFFF, // 336
	0xFFFF, // 337
	0xFFFF, // 338
	0xFFFF, // 339
	0xFFFF, // 340
	0xFFFF, // 341
	152,    // 342
	174,    // 343
	164,    // 344
	243,    // 345
	0xFFFF, // 346
	0xFFFF, // 347
	0xFFFF, // 348
	58,     // 349
	0xFFFF, // 350
	0xFFFF, // 351
	0xFFFF, // 352
	65,     // 353
	115,    // 354
	0xFFFF, // 355
	0xFFFF, // 356
	0xFFFF, // 357
	0xFFFF, // 358
	0xFFFF, // 359
	16,     // 360
	0xFFFF, // 361
	148,    // 362
	0xFFFF, // 363
	147,    // 364
	0xFFFF, // 365
	0xFFFF, // 366
	190,    // 367
	75,     // 368
	0xFFFF, // 369
	0xFFFF, // 370
	0xFFFF, // 371
	238,    // 372
	230,    // 373
	156,    // 374
	0xFFFF, // 375
	6,      // 376
	0xFFFF, // 377
	220,    // 378
	0xFFFF, // 379
	0xFFFF, // 380
	0xFFFF, // 381
	0xFFFF, // 382
	0xFFFF, // 383
	0xFFFF, // 384
	0xFFFF, // 385
	22,     // 386
	121,    // 387
	0xFFFF, // 388
	102,    // 389
	0xFFFF, // 390
	0xFFFF, // 391
	0xFFFF, // 392
	33,     // 393
	237,    // 394
	0xFFFF, // 395
	0xFFFF, // 396
	131,    // 397
	182,    // 398
	78,     // 399
	0xFFFF, // 400
	0xFFFF, // 401
	0xFFFF, // 402
	0xFFFF, // 403
	0xFFFF, // 404
	0xFFFF, // 405
	0xFFFF, // 406
	0xFFFF, // 407
	0xFFFF, // 408
	0xFFFF, // 409
	0xFFFF, // 410
	0xFFFF, // 411
	0xFFFF, // 412
	0xFFFF, // 413
	92,     // 414
	192,    // 415
	170,    // 416
	125,    // 417
	0xFFFF, // 418
	0xFFFF, // 419
	0xFFFF, // 420
	0xFFFF, // 421
	0xFFFF, // 422
	160,    // 423
	62,     // 424
	64,     // 425
	111,    // 426
	191,    // 427
	212,    // 428
	0xFFFF, // 429
	0xFFFF, // 430
	35,     // 431
	158,    // 432
	60,     // 433
	218,    // 434
	54,     // 435
	39,     // 436
	85,     // 437
	229,    // 438
	0xFFFF, // 439
	122,    // 440
	0xFFFF, // 441
	0xFFFF, // 442
	214,    // 443
	0xFFFF, // 444
	0xFFFF, // 445
	0xFFFF, // 446
	0xFFFF, // 447
	0xFFFF, // 448
	95,     // 449
	215,    // 450
	0xFFFF, // 451
	79,     // 452
	0xFFFF, // 453
	0xFFFF, // 454
	162,    // 455
	233,    // 456
	0xFFFF, // 457
	0xFFFF, // 458
	0xFFFF, // 459
	163,    // 460
	87,     // 461
	0xFFFF, // 462
	0xFFFF, // 463
	0xFFFF, // 464
	143,    // 465
	34,     // 466
	0xFFFF, // 467
	150,    // 468
	0xFFFF, // 469
	19,     // 470
	123,    // 471
	166,    // 472
	0xFFFF, // 473
	0xFFFF, // 474
	27,     // 475
	0xFFFF, // 476
	0xFFFF, // 477
	0xFFFF, // 478
	0xFFFF, // 479
	188,    // 480
	142,    // 481
	42,     // 482
	197,    // 483
	0xFFFF, // 484
	46,     // 485
	52,     // 486
	0xFFFF, // 487
	246,    // 488
	0xFFFF, // 489
	0xFFFF, // 490
	0xFFFF, // 491
	132,    // 492
	176,    // 493
	0xFFFF, // 494
	91,     // 495
	0xFFFF, // 496
	0xFFFF, // 497
	0xFFFF, // 498
	0xFFFF, // 499
	0xFFFF, // 500
	0xFFFF, // 501
	120,    // 502
	209,    // 503
	0xFFFF, // 504
	0xFFFF, // 505
	0xFFFF, // 506
	0xFFFF, // 507
	154,    // 508
	0xFFFF, // 509
	1,      // 510
	17,     // 511
}

// Country name keys (canonical names)
var nameKeys = [...]string{
	"Andorra",
	"United Arab Emirates",
	"Afghanistan",
	"Antigua and Barbuda",
	"Anguilla",
	"Albania",
	"Armenia",
	"Angola",
	"Antarctica",
	"Argentina",
	"American Samoa",
	"Austria",
	"Australia",
	"Aruba",
	"Åland Islands",
	"Azerbaijan",
	"Bosnia and Herzegovina",
	"Barbados",
	"Bangladesh",
	"Belgium",
	"Burkina Faso",
	"Bulgaria",
	"Bahrain",
	"Burundi",
	"Benin",
	"Saint Barthélemy",
	"Bermuda",
	"Brunei Darussalam",
	"Bolivia, Plurinational State of",
	"Bonaire, Sint Eustatius and Saba",
	"Brazil",
	"Bahamas",
	"Bhutan",
	"Bouvet Island",
	"Botswana",
	"Belarus",
	"Belize",
	"Canada",
	"Cocos (Keeling) Islands",
	"Congo, Democratic Republic of the",
	"Central African Republic",
	"Congo",
	"Switzerland",
	"Côte d'Ivoire",
	"Cook Islands",
	"Chile",
	"Cameroon",
	"China",
	"Colombia",
	"Costa Rica",
	"Cuba",
	"Cabo Verde",
	"Curaçao",
	"Christmas Island",
	"Cyprus",
	"Czechia",
	"Germany",
	"Djibouti",
	"Denmark",
	"Dominica",
	"Dominican Republic",
	"Algeria",
	"Ecuador",
	"Estonia",
	"Egypt",
	"Western Sahara",
	"Eritrea",
	"Spain",
	"Ethiopia",
	"Finland",
	"Fiji",
	"Falkland Islands (Malvinas)",
	"Micronesia, Federated States of",
	"Faroe Islands",
	"France",
	"Gabon",
	"United Kingdom of Great Britain and Northern Ireland",
	"Grenada",
	"Georgia",
	"French Guiana",
	"Guernsey",
	"Ghana",
	"Gibraltar",
	"Greenland",
	"Gambia",
	"Guinea",
	"Guadeloupe",
	"Equatorial Guinea",
	"Greece",
	"South Georgia and the South Sandwich Islands",
	"Guatemala",
	"Guam",
	"Guinea-Bissau",
	"Guyana",
	"Hong Kong",
	"Heard Island and McDonald Islands",
	"Honduras",
	"Croatia",
	"Haiti",
	"Hungary",
	"Indonesia",
	"Ireland",
	"Israel",
	"Isle of Man",
	"India",
	"British Indian Ocean Territory",
	"Iraq",
	"Iran, Islamic Republic of",
	"Iceland",
	"Italy",
	"Jersey",
	"Jamaica",
	"Jordan",
	"Japan",
	"Kenya",
	"Kyrgyzstan",
	"Cambodia",
	"Kiribati",
	"Comoros",
	"Saint Kitts and Nevis",
	"Korea, Democratic People's Republic of",
	"Korea, Republic of",
	"Kuwait",
	"Cayman Islands",
	"Kazakhstan",
	"Lao People's Democratic Republic",
	"Lebanon",
	"Saint Lucia",
	"Liechtenstein",
	"Sri Lanka",
	"Liberia",
	"Lesotho",
	"Lithuania",
	"Luxembourg",
	"Latvia",
	"Libya",
	"Morocco",
	"Monaco",
	"Moldova, Republic of",
	"Montenegro",
	"Saint Martin (French part)",
	"Madagascar",
	"Marshall Islands",
	"North Macedonia",
	"Mali",
	"Myanmar",
	"Mongolia",
	"Macao",
	"Northern Mariana Islands",
	"Martinique",
	"Mauritania",
	"Montserrat",
	"Malta",
	"Mauritius",
	"Maldives",
	"Malawi",
	"Mexico",
	"Malaysia",
	"Mozambique",
	"Namibia",
	"New Caledonia",
	"Niger",
	"Norfolk Island",
	"Nigeria",
	"Nicaragua",
	"Netherlands, Kingdom of the",
	"Norway",
	"Nepal",
	"Nauru",
	"Niue",
	"New Zealand",
	"Oman",
	"Panama",
	"Peru",
	"French Polynesia",
	"Papua New Guinea",
	"Philippines",
	"Pakistan",
	"Poland",
	"Saint Pierre and Miquelon",
	"Pitcairn",
	"Puerto Rico",
	"Palestine, State of",
	"Portugal",
	"Palau",
	"Paraguay",
	"Qatar",
	"Réunion",
	"Romania",
	"Serbia",
	"Russian Federation",
	"Rwanda",
	"Saudi Arabia",
	"Solomon Islands",
	"Seychelles",
	"Sudan",
	"Sweden",
	"Singapore",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Slovenia",
	"Svalbard and Jan Mayen",
	"Slovakia",
	"Sierra Leone",
	"San Marino",
	"Senegal",
	"Somalia",
	"Suriname",
	"South Sudan",
	"Sao Tome and Principe",
	"El Salvador",
	"Sint Maarten (Dutch part)",
	"Syrian Arab Republic",
	"Eswatini",
	"Turks and Caicos Islands",
	"Chad",
	"French Southern Territories",
	"Togo",
	"Thailand",
	"Tajikistan",
	"Tokelau",
	"Timor-Leste",
	"Turkmenistan",
	"Tunisia",
	"Tonga",
	"Türkiye",
	"Trinidad and Tobago",
	"Tuvalu",
	"Taiwan, Province of China",
	"Tanzania, United Republic of",
	"Ukraine",
	"Uganda",
	"United States Minor Outlying Islands",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Holy See",
	"Saint Vincent and the Grenadines",
	"Venezuela, Bolivarian Republic of",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Viet Nam",
	"Vanuatu",
	"Wallis and Futuna",
	"Samoa",
	"Yemen",
	"Mayotte",
	"South Africa",
	"Zambia",
	"Zimbabwe",
}

// Alpha-2 code values (uppercase)
var nameAlpha2Vals = [...]string{
	"AD",
	"AE",
	"AF",
	"AG",
	"AI",
	"AL",
	"AM",
	"AO",
	"AQ",
	"AR",
	"AS",
	"AT",
	"AU",
	"AW",
	"AX",
	"AZ",
	"BA",
	"BB",
	"BD",
	"BE",
	"BF",
	"BG",
	"BH",
	"BI",
	"BJ",
	"BL",
	"BM",
	"BN",
	"BO",
	"BQ",
	"BR",
	"BS",
	"BT",
	"BV",
	"BW",
	"BY",
	"BZ",
	"CA",
	"CC",
	"CD",
	"CF",
	"CG",
	"CH",
	"CI",
	"CK",
	"CL",
	"CM",
	"CN",
	"CO",
	"CR",
	"CU",
	"CV",
	"CW",
	"CX",
	"CY",
	"CZ",
	"DE",
	"DJ",
	"DK",
	"DM",
	"DO",
	"DZ",
	"EC",
	"EE",
	"EG",
	"EH",
	"ER",
	"ES",
	"ET",
	"FI",
	"FJ",
	"FK",
	"FM",
	"FO",
	"FR",
	"GA",
	"GB",
	"GD",
	"GE",
	"GF",
	"GG",
	"GH",
	"GI",
	"GL",
	"GM",
	"GN",
	"GP",
	"GQ",
	"GR",
	"GS",
	"GT",
	"GU",
	"GW",
	"GY",
	"HK",
	"HM",
	"HN",
	"HR",
	"HT",
	"HU",
	"ID",
	"IE",
	"IL",
	"IM",
	"IN",
	"IO",
	"IQ",
	"IR",
	"IS",
	"IT",
	"JE",
	"JM",
	"JO",
	"JP",
	"KE",
	"KG",
	"KH",
	"KI",
	"KM",
	"KN",
	"KP",
	"KR",
	"KW",
	"KY",
	"KZ",
	"LA",
	"LB",
	"LC",
	"LI",
	"LK",
	"LR",
	"LS",
	"LT",
	"LU",
	"LV",
	"LY",
	"MA",
	"MC",
	"MD",
	"ME",
	"MF",
	"MG",
	"MH",
	"MK",
	"ML",
	"MM",
	"MN",
	"MO",
	"MP",
	"MQ",
	"MR",
	"MS",
	"MT",
	"MU",
	"MV",
	"MW",
	"MX",
	"MY",
	"MZ",
	"NA",
	"NC",
	"NE",
	"NF",
	"NG",
	"NI",
	"NL",
	"NO",
	"NP",
	"NR",
	"NU",
	"NZ",
	"OM",
	"PA",
	"PE",
	"PF",
	"PG",
	"PH",
	"PK",
	"PL",
	"PM",
	"PN",
	"PR",
	"PS",
	"PT",
	"PW",
	"PY",
	"QA",
	"RE",
	"RO",
	"RS",
	"RU",
	"RW",
	"SA",
	"SB",
	"SC",
	"SD",
	"SE",
	"SG",
	"SH",
	"SI",
	"SJ",
	"SK",
	"SL",
	"SM",
	"SN",
	"SO",
	"SR",
	"SS",
	"ST",
	"SV",
	"SX",
	"SY",
	"SZ",
	"TC",
	"TD",
	"TF",
	"TG",
	"TH",
	"TJ",
	"TK",
	"TL",
	"TM",
	"TN",
	"TO",
	"TR",
	"TT",
	"TV",
	"TW",
	"TZ",
	"UA",
	"UG",
	"UM",
	"US",
	"UY",
	"UZ",
	"VA",
	"VC",
	"VE",
	"VG",
	"VI",
	"VN",
	"VU",
	"WF",
	"WS",
	"YE",
	"YT",
	"ZA",
	"ZM",
	"ZW",
}

// Alpha-3 code values (uppercase)
var nameAlpha3Vals = [...]string{
	"AND",
	"ARE",
	"AFG",
	"ATG",
	"AIA",
	"ALB",
	"ARM",
	"AGO",
	"ATA",
	"ARG",
	"ASM",
	"AUT",
	"AUS",
	"ABW",
	"ALA",
	"AZE",
	"BIH",
	"BRB",
	"BGD",
	"BEL",
	"BFA",
	"BGR",
	"BHR",
	"BDI",
	"BEN",
	"BLM",
	"BMU",
	"BRN",
	"BOL",
	"BES",
	"BRA",
	"BHS",
	"BTN",
	"BVT",
	"BWA",
	"BLR",
	"BLZ",
	"CAN",
	"CCK",
	"COD",
	"CAF",
	"COG",
	"CHE",
	"CIV",
	"COK",
	"CHL",
	"CMR",
	"CHN",
	"COL",
	"CRI",
	"CUB",
	"CPV",
	"CUW",
	"CXR",
	"CYP",
	"CZE",
	"DEU",
	"DJI",
	"DNK",
	"DMA",
	"DOM",
	"DZA",
	"ECU",
	"EST",
	"EGY",
	"ESH",
	"ERI",
	"ESP",
	"ETH",
	"FIN",
	"FJI",
	"FLK",
	"FSM",
	"FRO",
	"FRA",
	"GAB",
	"GBR",
	"GRD",
	"GEO",
	"GUF",
	"GGY",
	"GHA",
	"GIB",
	"GRL",
	"GMB",
	"GIN",
	"GLP",
	"GNQ",
	"GRC",
	"SGS",
	"GTM",
	"GUM",
	"GNB",
	"GUY",
	"HKG",
	"HMD",
	"HND",
	"HRV",
	"HTI",
	"HUN",
	"IDN",
	"IRL",
	"ISR",
	"IMN",
	"IND",
	"IOT",
	"IRQ",
	"IRN",
	"ISL",
	"ITA",
	"JEY",
	"JAM",
	"JOR",
	"JPN",
	"KEN",
	"KGZ",
	"KHM",
	"KIR",
	"COM",
	"KNA",
	"PRK",
	"KOR",
	"KWT",
	"CYM",
	"KAZ",
	"LAO",
	"LBN",
	"LCA",
	"LIE",
	"LKA",
	"LBR",
	"LSO",
	"LTU",
	"LUX",
	"LVA",
	"LBY",
	"MAR",
	"MCO",
	"MDA",
	"MNE",
	"MAF",
	"MDG",
	"MHL",
	"MKD",
	"MLI",
	"MMR",
	"MNG",
	"MAC",
	"MNP",
	"MTQ",
	"MRT",
	"MSR",
	"MLT",
	"MUS",
	"MDV",
	"MWI",
	"MEX",
	"MYS",
	"MOZ",
	"NAM",
	"NCL",
	"NER",
	"NFK",
	"NGA",
	"NIC",
	"NLD",
	"NOR",
	"NPL",
	"NRU",
	"NIU",
	"NZL",
	"OMN",
	"PAN",
	"PER",
	"PYF",
	"PNG",
	"PHL",
	"PAK",
	"POL",
	"SPM",
	"PCN",
	"PRI",
	"PSE",
	"PRT",
	"PLW",
	"PRY",
	"QAT",
	"REU",
	"ROU",
	"SRB",
	"RUS",
	"RWA",
	"SAU",
	"SLB",
	"SYC",
	"SDN",
	"SWE",
	"SGP",
	"SHN",
	"SVN",
	"SJM",
	"SVK",
	"SLE",
	"SMR",
	"SEN",
	"SOM",
	"SUR",
	"SSD",
	"STP",
	"SLV",
	"SXM",
	"SYR",
	"SWZ",
	"TCA",
	"TCD",
	"ATF",
	"TGO",
	"THA",
	"TJK",
	"TKL",
	"TLS",
	"TKM",
	"TUN",
	"TON",
	"TUR",
	"TTO",
	"TUV",
	"TWN",
	"TZA",
	"UKR",
	"UGA",
	"UMI",
	"USA",
	"URY",
	"UZB",
	"VAT",
	"VCT",
	"VEN",
	"VGB",
	"VIR",
	"VNM",
	"VUT",
	"WLF",
	"WSM",
	"YEM",
	"MYT",
	"ZAF",
	"ZMB",
	"ZWE",
}

// Numeric code values (as integers)
var nameNumberVals = [...]int{
	20,
	784,
	4,
	28,
	660,
	8,
	51,
	24,
	10,
	32,
	16,
	40,
	36,
	533,
	248,
	31,
	70,
	52,
	50,
	56,
	854,
	100,
	48,
	108,
	204,
	652,
	60,
	96,
	68,
	535,
	76,
	44,
	64,
	74,
	72,
	112,
	84,
	124,
	166,
	180,
	140,
	178,
	756,
	384,
	184,
	152,
	120,
	156,
	170,
	188,
	192,
	132,
	531,
	162,
	196,
	203,
	276,
	262,
	208,
	212,
	214,
	12,
	218,
	233,
	818,
	732,
	232,
	724,
	231,
	246,
	242,
	238,
	583,
	234,
	250,
	266,
	826,
	308,
	268,
	254,
	831,
	288,
	292,
	304,
	270,
	324,
	312,
	226,
	300,
	239,
	320,
	316,
	624,
	328,
	344,
	334,
	340,
	191,
	332,
	348,
	360,
	372,
	376,
	833,
	356,
	86,
	368,
	364,
	352,
	380,
	832,
	388,
	400,
	392,
	404,
	417,
	116,
	296,
	174,
	659,
	408,
	410,
	414,
	136,
	398,
	418,
	422,
	662,
	438,
	144,
	430,
	426,
	440,
	442,
	428,
	434,
	504,
	492,
	498,
	499,
	663,
	450,
	584,
	807,
	466,
	104,
	496,
	446,
	580,
	474,
	478,
	500,
	470,
	480,
	462,
	454,
	484,
	458,
	508,
	516,
	540,
	562,
	574,
	566,
	558,
	528,
	578,
	524,
	520,
	570,
	554,
	512,
	591,
	604,
	258,
	598,
	608,
	586,
	616,
	666,
	612,
	630,
	275,
	620,
	585,
	600,
	634,
	638,
	642,
	688,
	643,
	646,
	682,
	90,
	690,
	729,
	752,
	702,
	654,
	705,
	744,
	703,
	694,
	674,
	686,
	706,
	740,
	728,
	678,
	222,
	534,
	760,
	748,
	796,
	148,
	260,
	768,
	764,
	762,
	772,
	626,
	795,
	788,
	776,
	792,
	780,
	798,
	158,
	834,
	804,
	800,
	581,
	840,
	858,
	860,
	336,
	670,
	862,
	92,
	850,
	704,
	548,
	876,
	882,
	887,
	175,
	710,
	894,
	716,
}

// NameToAlpha2 retrieves the ISO 3166-1 alpha-2 code for a country name.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The lookup is case-insensitive.
//
// Parameters:
//   - name: Country name (e.g., "Germany", "FRANCE", "italy")
//
// Returns:
//   - string: The corresponding alpha-2 code in uppercase if found
//   - bool: true if the name exists, false otherwise
//
// Example:
//
//	if alpha2, ok := NameToAlpha2("germany"); ok {
//	    fmt.Println(alpha2) // Output: DE
//	}
func NameToAlpha2(name string) (string, bool) {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return "", false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				return nameAlpha2Vals[j], true
			}
		}
		i = (i + 1) & nameMask
	}
	return "", false
}

// NameToAlpha3 retrieves the ISO 3166-1 alpha-3 code for a country name.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The lookup is case-insensitive.
//
// Parameters:
//   - name: Country name (e.g., "Netherlands", "BELGIUM", "spain")
//
// Returns:
//   - string: The corresponding alpha-3 code in uppercase if found
//   - bool: true if the name exists, false otherwise
//
// Example:
//
//	if alpha3, ok := NameToAlpha3("netherlands"); ok {
//	    fmt.Println(alpha3) // Output: NLD
//	}
func NameToAlpha3(name string) (string, bool) {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return "", false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				return nameAlpha3Vals[j], true
			}
		}
		i = (i + 1) & nameMask
	}
	return "", false
}

// NameToNumber retrieves the UN M.49 numeric code for a country name.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The lookup is case-insensitive.
//
// Parameters:
//   - name: Country name (e.g., "France", "ITALY", "poland")
//
// Returns:
//   - string: The UN M.49 numeric code with leading zeros if found
//   - bool: true if the name exists, false otherwise
//
// Example:
//
//	if num, ok := NameToNumber("france"); ok {
//	    fmt.Println(num) // Output: 250
//	}
//
// Note: For integer results, use NameToNumberInt for better performance.
func NameToNumber(name string) (string, bool) {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return "", false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				return formatNumber(nameNumberVals[j]), true
			}
		}
		i = (i + 1) & nameMask
	}
	return "", false
}

// NameToNumberInt retrieves the UN M.49 numeric code for a country name as an integer.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The lookup is case-insensitive.
//
// Parameters:
//   - name: Country name (e.g., "Sweden", "DENMARK", "norway")
//
// Returns:
//   - int: The UN M.49 numeric code as integer if found
//   - bool: true if the name exists, false otherwise
//
// Example:
//
//	if num, ok := NameToNumberInt("sweden"); ok {
//	    fmt.Println(num) // Output: 752
//	}
func NameToNumberInt(name string) (int, bool) {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return 0, false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				return nameNumberVals[j], true
			}
		}
		i = (i + 1) & nameMask
	}
	return 0, false
}

// GetByName retrieves complete country information by country name.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The lookup is case-insensitive.
//
// Parameters:
//   - name: Country name (e.g., "Switzerland", "AUSTRIA", "portugal")
//
// Returns:
//   - Country: Complete country information with properly formatted codes if found
//   - bool: true if the name exists, false otherwise
//
// Example:
//
//	if country, ok := GetByName("switzerland"); ok {
//	    fmt.Printf("%s has alpha-2 code %s\n", country.Name, country.Alpha2)
//	}
func GetByName(name string) (Country, bool) {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return Country{}, false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				// Use the alpha-2 code to get the full country data
				return GetByAlpha2(nameAlpha2Vals[j])
			}
		}
		i = (i + 1) & nameMask
	}
	return Country{}, false
}

// IsValidName validates whether the given string is a valid country name.
//
// This function uses a hash table with linear probing for O(1) average-case
// lookups with zero allocations. The validation is case-insensitive.
//
// Parameters:
//   - name: String to validate as a country name (e.g., "Germany", "france")
//
// Returns:
//   - bool: true if the name is a valid country name, false otherwise
//
// Example:
//
//	if IsValidName("germany") {
//	    // Process valid country name
//	    alpha2, _ := NameToAlpha2("germany")
//	    fmt.Println(alpha2)
//	}
func IsValidName(name string) bool {
	h := hashCI(name)
	i := int(h & nameMask)
	for steps := 0; steps <= nameMask; steps++ {
		if nameSlotIdx[i] == 0xFFFF {
			return false
		}
		if nameSlotHash[i] == h {
			j := int(nameSlotIdx[i])
			if eqCI(name, nameKeys[j]) {
				return true
			}
		}
		i = (i + 1) & nameMask
	}
	return false
}
