// Code generated by go generate; DO NOT EDIT.

package countrycodes

// IsValidAlpha2 validates whether the given string is a valid ISO 3166-1 alpha-2 code.
//
// This function performs an O(1) lookup using packed keys for zero-allocation,
// case-insensitive validation. Use this to validate user input before conversions.
// The validation is case-insensitive.
//
// Parameters:
//   - code: String to validate as an ISO 3166-1 alpha-2 code (e.g., "FR", "de")
//
// Returns:
//   - bool: true if the code is a valid ISO 3166-1 alpha-2 code, false otherwise
//
// Example:
//
//	if IsValidAlpha2("fr") {
//	    // Process valid country code
//	    alpha3, _ := Alpha2ToAlpha3("fr")
//	    fmt.Println(alpha3)
//	}
func IsValidAlpha2(code string) bool {
	if len(code) != 2 {
		return false
	}
	// Inline key generation for better performance
	key := uint16(lowerASCII(code[0])) | uint16(lowerASCII(code[1]))<<8
	_, ok := alpha2ToAlpha3Map[key]
	return ok
}

// IsValidAlpha3 validates whether the given string is a valid ISO 3166-1 alpha-3 code.
//
// This function performs an O(1) lookup using packed keys for zero-allocation,
// case-insensitive validation. Use this to validate user input before conversions.
// The validation is case-insensitive.
//
// Parameters:
//   - code: String to validate as an ISO 3166-1 alpha-3 code (e.g., "ITA", "esp")
//
// Returns:
//   - bool: true if the code is a valid ISO 3166-1 alpha-3 code, false otherwise
//
// Example:
//
//	if IsValidAlpha3("ita") {
//	    // Process valid country code
//	    alpha2, _ := Alpha3ToAlpha2("ita")
//	    fmt.Println(alpha2)
//	}
func IsValidAlpha3(code string) bool {
	if len(code) != 3 {
		return false
	}
	// Inline key generation for better performance
	key := uint32(lowerASCII(code[0])) | uint32(lowerASCII(code[1]))<<8 | uint32(lowerASCII(code[2]))<<16
	_, ok := alpha3ToAlpha2Map[key]
	return ok
}

// IsValidNumber validates whether the given string is a valid UN M.49 numeric code.
//
// This function performs an O(1) map lookup with zero memory allocations.
// The function accepts numeric codes with leading zeros.
//
// Parameters:
//   - code: String to validate as a UN M.49 numeric code (e.g., "276", "380")
//
// Returns:
//   - bool: true if the code is a valid UN M.49 numeric code, false otherwise
//
// Example:
//
//	if IsValidNumber("276") {
//	    // Process valid numeric code
//	    alpha2, _ := NumberToAlpha2("276")
//	    fmt.Println(alpha2)
//	}
//
// Note: For integer validation, use IsValidNumberInt for better performance.
func IsValidNumber(code string) bool {
	_, ok := numberToAlpha2Map[code]
	return ok
}
