// Code generated by generator; DO NOT EDIT.

package alpha3

// ISO 3166-1 alpha-3 country code constants.
// These constants provide compile-time type safety and IDE autocomplete support.
//
// Usage:
//
//	import "github.com/flaticols/countrycodes/alpha3"
//
//	name, _ := countrycodes.Alpha3ToName(alpha3.Netherlands)
//	alpha2, _ := countrycodes.Alpha3ToAlpha2(alpha3.France)
const (
	// Andorra - Andorra
	Andorra = "AND"
	// UnitedArabEmirates - United Arab Emirates
	UnitedArabEmirates = "ARE"
	// Afghanistan - Afghanistan
	Afghanistan = "AFG"
	// AntiguaBarbuda - Antigua and Barbuda
	AntiguaBarbuda = "ATG"
	// Anguilla - Anguilla
	Anguilla = "AIA"
	// Albania - Albania
	Albania = "ALB"
	// Armenia - Armenia
	Armenia = "ARM"
	// Angola - Angola
	Angola = "AGO"
	// Antarctica - Antarctica
	Antarctica = "ATA"
	// Argentina - Argentina
	Argentina = "ARG"
	// AmericanSamoa - American Samoa
	AmericanSamoa = "ASM"
	// Austria - Austria
	Austria = "AUT"
	// Australia - Australia
	Australia = "AUS"
	// Aruba - Aruba
	Aruba = "ABW"
	// AlandIslands - Åland Islands
	AlandIslands = "ALA"
	// Azerbaijan - Azerbaijan
	Azerbaijan = "AZE"
	// BosniaHerzegovina - Bosnia and Herzegovina
	BosniaHerzegovina = "BIH"
	// Barbados - Barbados
	Barbados = "BRB"
	// Bangladesh - Bangladesh
	Bangladesh = "BGD"
	// Belgium - Belgium
	Belgium = "BEL"
	// BurkinaFaso - Burkina Faso
	BurkinaFaso = "BFA"
	// Bulgaria - Bulgaria
	Bulgaria = "BGR"
	// Bahrain - Bahrain
	Bahrain = "BHR"
	// Burundi - Burundi
	Burundi = "BDI"
	// Benin - Benin
	Benin = "BEN"
	// SaintBarthelemy - Saint Barthélemy
	SaintBarthelemy = "BLM"
	// Bermuda - Bermuda
	Bermuda = "BMU"
	// Brunei - Brunei Darussalam
	Brunei = "BRN"
	// Bolivia - Bolivia, Plurinational State of
	Bolivia = "BOL"
	// CaribbeanNetherlands - Bonaire, Sint Eustatius and Saba
	CaribbeanNetherlands = "BES"
	// Brazil - Brazil
	Brazil = "BRA"
	// Bahamas - Bahamas
	Bahamas = "BHS"
	// Bhutan - Bhutan
	Bhutan = "BTN"
	// BouvetIsland - Bouvet Island
	BouvetIsland = "BVT"
	// Botswana - Botswana
	Botswana = "BWA"
	// Belarus - Belarus
	Belarus = "BLR"
	// Belize - Belize
	Belize = "BLZ"
	// Canada - Canada
	Canada = "CAN"
	// CocosIslands - Cocos (Keeling) Islands
	CocosIslands = "CCK"
	// CongoDRC - Congo, Democratic Republic of the
	CongoDRC = "COD"
	// CentralAfricanRepublic - Central African Republic
	CentralAfricanRepublic = "CAF"
	// CongoBrazzaville - Congo
	CongoBrazzaville = "COG"
	// Switzerland - Switzerland
	Switzerland = "CHE"
	// CoteDIvoire - Côte d'Ivoire
	CoteDIvoire = "CIV"
	// CookIslands - Cook Islands
	CookIslands = "COK"
	// Chile - Chile
	Chile = "CHL"
	// Cameroon - Cameroon
	Cameroon = "CMR"
	// China - China
	China = "CHN"
	// Colombia - Colombia
	Colombia = "COL"
	// CostaRica - Costa Rica
	CostaRica = "CRI"
	// Cuba - Cuba
	Cuba = "CUB"
	// CapeVerde - Cabo Verde
	CapeVerde = "CPV"
	// Curacao - Curaçao
	Curacao = "CUW"
	// ChristmasIsland - Christmas Island
	ChristmasIsland = "CXR"
	// Cyprus - Cyprus
	Cyprus = "CYP"
	// CzechRepublic - Czechia
	CzechRepublic = "CZE"
	// Germany - Germany
	Germany = "DEU"
	// Djibouti - Djibouti
	Djibouti = "DJI"
	// Denmark - Denmark
	Denmark = "DNK"
	// Dominica - Dominica
	Dominica = "DMA"
	// DominicanRepublic - Dominican Republic
	DominicanRepublic = "DOM"
	// Algeria - Algeria
	Algeria = "DZA"
	// Ecuador - Ecuador
	Ecuador = "ECU"
	// Estonia - Estonia
	Estonia = "EST"
	// Egypt - Egypt
	Egypt = "EGY"
	// WesternSahara - Western Sahara
	WesternSahara = "ESH"
	// Eritrea - Eritrea
	Eritrea = "ERI"
	// Spain - Spain
	Spain = "ESP"
	// Ethiopia - Ethiopia
	Ethiopia = "ETH"
	// Finland - Finland
	Finland = "FIN"
	// Fiji - Fiji
	Fiji = "FJI"
	// FalklandIslands - Falkland Islands (Malvinas)
	FalklandIslands = "FLK"
	// Micronesia - Micronesia, Federated States of
	Micronesia = "FSM"
	// FaroeIslands - Faroe Islands
	FaroeIslands = "FRO"
	// France - France
	France = "FRA"
	// Gabon - Gabon
	Gabon = "GAB"
	// UnitedKingdom - United Kingdom of Great Britain and Northern Ireland
	UnitedKingdom = "GBR"
	// Grenada - Grenada
	Grenada = "GRD"
	// Georgia - Georgia
	Georgia = "GEO"
	// FrenchGuiana - French Guiana
	FrenchGuiana = "GUF"
	// Guernsey - Guernsey
	Guernsey = "GGY"
	// Ghana - Ghana
	Ghana = "GHA"
	// Gibraltar - Gibraltar
	Gibraltar = "GIB"
	// Greenland - Greenland
	Greenland = "GRL"
	// Gambia - Gambia
	Gambia = "GMB"
	// Guinea - Guinea
	Guinea = "GIN"
	// Guadeloupe - Guadeloupe
	Guadeloupe = "GLP"
	// EquatorialGuinea - Equatorial Guinea
	EquatorialGuinea = "GNQ"
	// Greece - Greece
	Greece = "GRC"
	// SouthGeorgiaAndSouthSandwichIslands - South Georgia and the South Sandwich Islands
	SouthGeorgiaAndSouthSandwichIslands = "SGS"
	// Guatemala - Guatemala
	Guatemala = "GTM"
	// Guam - Guam
	Guam = "GUM"
	// GuineaBissau - Guinea-Bissau
	GuineaBissau = "GNB"
	// Guyana - Guyana
	Guyana = "GUY"
	// HongKong - Hong Kong
	HongKong = "HKG"
	// HeardAndMcDonaldIslands - Heard Island and McDonald Islands
	HeardAndMcDonaldIslands = "HMD"
	// Honduras - Honduras
	Honduras = "HND"
	// Croatia - Croatia
	Croatia = "HRV"
	// Haiti - Haiti
	Haiti = "HTI"
	// Hungary - Hungary
	Hungary = "HUN"
	// Indonesia - Indonesia
	Indonesia = "IDN"
	// Ireland - Ireland
	Ireland = "IRL"
	// Israel - Israel
	Israel = "ISR"
	// IsleMan - Isle of Man
	IsleMan = "IMN"
	// India - India
	India = "IND"
	// BritishIndianOceanTerritory - British Indian Ocean Territory
	BritishIndianOceanTerritory = "IOT"
	// Iraq - Iraq
	Iraq = "IRQ"
	// Iran - Iran, Islamic Republic of
	Iran = "IRN"
	// Iceland - Iceland
	Iceland = "ISL"
	// Italy - Italy
	Italy = "ITA"
	// Jersey - Jersey
	Jersey = "JEY"
	// Jamaica - Jamaica
	Jamaica = "JAM"
	// Jordan - Jordan
	Jordan = "JOR"
	// Japan - Japan
	Japan = "JPN"
	// Kenya - Kenya
	Kenya = "KEN"
	// Kyrgyzstan - Kyrgyzstan
	Kyrgyzstan = "KGZ"
	// Cambodia - Cambodia
	Cambodia = "KHM"
	// Kiribati - Kiribati
	Kiribati = "KIR"
	// Comoros - Comoros
	Comoros = "COM"
	// SaintKittsNevis - Saint Kitts and Nevis
	SaintKittsNevis = "KNA"
	// NorthKorea - Korea, Democratic People's Republic of
	NorthKorea = "PRK"
	// SouthKorea - Korea, Republic of
	SouthKorea = "KOR"
	// Kuwait - Kuwait
	Kuwait = "KWT"
	// CaymanIslands - Cayman Islands
	CaymanIslands = "CYM"
	// Kazakhstan - Kazakhstan
	Kazakhstan = "KAZ"
	// Laos - Lao People's Democratic Republic
	Laos = "LAO"
	// Lebanon - Lebanon
	Lebanon = "LBN"
	// SaintLucia - Saint Lucia
	SaintLucia = "LCA"
	// Liechtenstein - Liechtenstein
	Liechtenstein = "LIE"
	// SriLanka - Sri Lanka
	SriLanka = "LKA"
	// Liberia - Liberia
	Liberia = "LBR"
	// Lesotho - Lesotho
	Lesotho = "LSO"
	// Lithuania - Lithuania
	Lithuania = "LTU"
	// Luxembourg - Luxembourg
	Luxembourg = "LUX"
	// Latvia - Latvia
	Latvia = "LVA"
	// Libya - Libya
	Libya = "LBY"
	// Morocco - Morocco
	Morocco = "MAR"
	// Monaco - Monaco
	Monaco = "MCO"
	// Moldova - Moldova, Republic of
	Moldova = "MDA"
	// Montenegro - Montenegro
	Montenegro = "MNE"
	// SaintMartinFrench - Saint Martin (French part)
	SaintMartinFrench = "MAF"
	// Madagascar - Madagascar
	Madagascar = "MDG"
	// MarshallIslands - Marshall Islands
	MarshallIslands = "MHL"
	// NorthMacedonia - North Macedonia
	NorthMacedonia = "MKD"
	// Mali - Mali
	Mali = "MLI"
	// Myanmar - Myanmar
	Myanmar = "MMR"
	// Mongolia - Mongolia
	Mongolia = "MNG"
	// Macau - Macao
	Macau = "MAC"
	// NorthernMarianaIslands - Northern Mariana Islands
	NorthernMarianaIslands = "MNP"
	// Martinique - Martinique
	Martinique = "MTQ"
	// Mauritania - Mauritania
	Mauritania = "MRT"
	// Montserrat - Montserrat
	Montserrat = "MSR"
	// Malta - Malta
	Malta = "MLT"
	// Mauritius - Mauritius
	Mauritius = "MUS"
	// Maldives - Maldives
	Maldives = "MDV"
	// Malawi - Malawi
	Malawi = "MWI"
	// Mexico - Mexico
	Mexico = "MEX"
	// Malaysia - Malaysia
	Malaysia = "MYS"
	// Mozambique - Mozambique
	Mozambique = "MOZ"
	// Namibia - Namibia
	Namibia = "NAM"
	// NewCaledonia - New Caledonia
	NewCaledonia = "NCL"
	// Niger - Niger
	Niger = "NER"
	// NorfolkIsland - Norfolk Island
	NorfolkIsland = "NFK"
	// Nigeria - Nigeria
	Nigeria = "NGA"
	// Nicaragua - Nicaragua
	Nicaragua = "NIC"
	// Netherlands - Netherlands, Kingdom of the
	Netherlands = "NLD"
	// Norway - Norway
	Norway = "NOR"
	// Nepal - Nepal
	Nepal = "NPL"
	// Nauru - Nauru
	Nauru = "NRU"
	// Niue - Niue
	Niue = "NIU"
	// NewZealand - New Zealand
	NewZealand = "NZL"
	// Oman - Oman
	Oman = "OMN"
	// Panama - Panama
	Panama = "PAN"
	// Peru - Peru
	Peru = "PER"
	// FrenchPolynesia - French Polynesia
	FrenchPolynesia = "PYF"
	// PapuaNewGuinea - Papua New Guinea
	PapuaNewGuinea = "PNG"
	// Philippines - Philippines
	Philippines = "PHL"
	// Pakistan - Pakistan
	Pakistan = "PAK"
	// Poland - Poland
	Poland = "POL"
	// SaintPierreAndMiquelon - Saint Pierre and Miquelon
	SaintPierreAndMiquelon = "SPM"
	// Pitcairn - Pitcairn
	Pitcairn = "PCN"
	// PuertoRico - Puerto Rico
	PuertoRico = "PRI"
	// Palestine - Palestine, State of
	Palestine = "PSE"
	// Portugal - Portugal
	Portugal = "PRT"
	// Palau - Palau
	Palau = "PLW"
	// Paraguay - Paraguay
	Paraguay = "PRY"
	// Qatar - Qatar
	Qatar = "QAT"
	// Reunion - Réunion
	Reunion = "REU"
	// Romania - Romania
	Romania = "ROU"
	// Serbia - Serbia
	Serbia = "SRB"
	// Russia - Russian Federation
	Russia = "RUS"
	// Rwanda - Rwanda
	Rwanda = "RWA"
	// SaudiArabia - Saudi Arabia
	SaudiArabia = "SAU"
	// SolomonIslands - Solomon Islands
	SolomonIslands = "SLB"
	// Seychelles - Seychelles
	Seychelles = "SYC"
	// Sudan - Sudan
	Sudan = "SDN"
	// Sweden - Sweden
	Sweden = "SWE"
	// Singapore - Singapore
	Singapore = "SGP"
	// SaintHelena - Saint Helena, Ascension and Tristan da Cunha
	SaintHelena = "SHN"
	// Slovenia - Slovenia
	Slovenia = "SVN"
	// SvalbardAndJanMayen - Svalbard and Jan Mayen
	SvalbardAndJanMayen = "SJM"
	// Slovakia - Slovakia
	Slovakia = "SVK"
	// SierraLeone - Sierra Leone
	SierraLeone = "SLE"
	// SanMarino - San Marino
	SanMarino = "SMR"
	// Senegal - Senegal
	Senegal = "SEN"
	// Somalia - Somalia
	Somalia = "SOM"
	// Suriname - Suriname
	Suriname = "SUR"
	// SouthSudan - South Sudan
	SouthSudan = "SSD"
	// SaoTomePrincipe - Sao Tome and Principe
	SaoTomePrincipe = "STP"
	// ElSalvador - El Salvador
	ElSalvador = "SLV"
	// SintMaartenDutch - Sint Maarten (Dutch part)
	SintMaartenDutch = "SXM"
	// Syria - Syrian Arab Republic
	Syria = "SYR"
	// Eswatini - Eswatini
	Eswatini = "SWZ"
	// TurksAndCaicosIslands - Turks and Caicos Islands
	TurksAndCaicosIslands = "TCA"
	// Chad - Chad
	Chad = "TCD"
	// FrenchSouthernTerritories - French Southern Territories
	FrenchSouthernTerritories = "ATF"
	// Togo - Togo
	Togo = "TGO"
	// Thailand - Thailand
	Thailand = "THA"
	// Tajikistan - Tajikistan
	Tajikistan = "TJK"
	// Tokelau - Tokelau
	Tokelau = "TKL"
	// TimorLeste - Timor-Leste
	TimorLeste = "TLS"
	// Turkmenistan - Turkmenistan
	Turkmenistan = "TKM"
	// Tunisia - Tunisia
	Tunisia = "TUN"
	// Tonga - Tonga
	Tonga = "TON"
	// Turkiye - Türkiye
	Turkiye = "TUR"
	// TrinidadTobago - Trinidad and Tobago
	TrinidadTobago = "TTO"
	// Tuvalu - Tuvalu
	Tuvalu = "TUV"
	// Taiwan - Taiwan, Province of China
	Taiwan = "TWN"
	// Tanzania - Tanzania, United Republic of
	Tanzania = "TZA"
	// Ukraine - Ukraine
	Ukraine = "UKR"
	// Uganda - Uganda
	Uganda = "UGA"
	// USMinorOutlyingIslands - United States Minor Outlying Islands
	USMinorOutlyingIslands = "UMI"
	// UnitedStates - United States of America
	UnitedStates = "USA"
	// Uruguay - Uruguay
	Uruguay = "URY"
	// Uzbekistan - Uzbekistan
	Uzbekistan = "UZB"
	// VaticanCity - Holy See
	VaticanCity = "VAT"
	// SaintVincentGrenadines - Saint Vincent and the Grenadines
	SaintVincentGrenadines = "VCT"
	// Venezuela - Venezuela, Bolivarian Republic of
	Venezuela = "VEN"
	// BritishVirginIslands - Virgin Islands (British)
	BritishVirginIslands = "VGB"
	// USVirginIslands - Virgin Islands (U.S.)
	USVirginIslands = "VIR"
	// Vietnam - Viet Nam
	Vietnam = "VNM"
	// Vanuatu - Vanuatu
	Vanuatu = "VUT"
	// WallisAndFutuna - Wallis and Futuna
	WallisAndFutuna = "WLF"
	// Samoa - Samoa
	Samoa = "WSM"
	// Yemen - Yemen
	Yemen = "YEM"
	// Mayotte - Mayotte
	Mayotte = "MYT"
	// SouthAfrica - South Africa
	SouthAfrica = "ZAF"
	// Zambia - Zambia
	Zambia = "ZMB"
	// Zimbabwe - Zimbabwe
	Zimbabwe = "ZWE"
)
